//! Emits the published bitconditions as data, for the tests to solve.

use crate::ubc::UBCS;

pub fn emit() -> String {
    let mut out = String::from(
        "//! The published bitconditions, as data for the tests.\n\
         //!\n\
         //! @generated by `codegen/` — do not edit by hand. Edit the table in\n\
         //! `codegen/src/ubc.rs` and re-run it.\n\
         //!\n\
         //! Each entry is `(i, a, j, b, c, dvs)`: bit `a` of `w[i]` XOR bit `b` of\n\
         //! `w[j]` must equal `c`, or every DV in `dvs` is ruled out.\n\
         //!\n\
         //! The check does not use these. It uses a different basis of the same\n\
         //! space, chosen to suit vector code. The tests use the published form\n\
         //! because it is per DV: solving the entries for one DV gives a message\n\
         //! that keeps that DV alive, and so reaches the checks behind it.\n\
         \n\
         #![forbid(unsafe_code)]\n\
         \n",
    );

    out.push_str(&format!(
        "/// The conditions, in the order they were published.\n\
         pub(super) const CONDITIONS: [(u8, u8, u8, u8, u8, u32); {}] = [\n",
        UBCS.len()
    ));
    for u in UBCS {
        out.push_str(&format!(
            "    ({}, {}, {}, {}, {}, {:#010x}),\n",
            u.i, u.a, u.j, u.b, u.c, u.dvs
        ));
    }
    out.push_str("];\n");
    out
}
