//! Shared helpers for the emitters.
//!
//! [`crate::solve`] decides which checks run in the prefix. Everything here
//! is about turning that decision into source.

use crate::solve::Family;
use crate::ubc::DV_NAMES;

/// How the two words are lined up so that one bit test covers both. Returns
/// the shift to apply and the bit to test. A positive shift moves `far` down,
/// a negative shift moves `near` down.
pub fn align(f: &Family) -> (i32, u32) {
    if f.far_bit >= f.near_bit {
        ((f.far_bit - f.near_bit) as i32, f.near_bit)
    } else {
        (-((f.near_bit - f.far_bit) as i32), f.far_bit)
    }
}

/// The DV bits as source, for example `DV_I_43_0_BIT | DV_I_45_0_BIT`.
pub fn dv_expr(dvs: u32) -> String {
    let names: Vec<&str> = (0..32)
        .filter(|n| dvs >> n & 1 == 1)
        .map(|n| DV_NAMES[n])
        .collect();
    names.join(" | ")
}

/// The header at the top of every generated file.
pub fn header(what: &str) -> String {
    format!(
        "//! {what}\n\
         //!\n\
         //! @generated by `codegen/` — do not edit by hand. Edit the table in\n\
         //! `codegen/src/ubc.rs` or the solver in `codegen/src/solve.rs` and\n\
         //! re-run it.\n\
         \n\
         use crate::ubc_check::*;\n"
    )
}
