//! Shared helpers for the emitters.
//!
//! [`crate::solve`] decides which checks run in the prefix and how they group.
//! Everything here is about turning that decision into source: lining up the
//! two bits, cutting a family into vector-sized pieces, and ordering the
//! pieces.

use crate::solve::{Family, Plan};
use crate::ubc::DV_NAMES;

/// Words in the expanded message schedule. Every emitted form takes
/// `&[u32; SCHEDULE]`, and a read past it is out of bounds.
const SCHEDULE: usize = 80;

/// How the two words are lined up so that one bit test covers both. Returns
/// the shift to apply and the bit to test. A positive shift moves `far` down,
/// a negative shift moves `near` down.
pub fn align(f: &Family) -> (i32, u32) {
    if f.far_bit >= f.near_bit {
        ((f.far_bit - f.near_bit) as i32, f.near_bit)
    } else {
        (-((f.near_bit - f.far_bit) as i32), f.far_bit)
    }
}

/// The DV bits as source, for example `DV_I_43_0_BIT | DV_I_45_0_BIT`.
pub fn dv_expr(dvs: u32) -> String {
    let names: Vec<&str> = (0..32)
        .filter(|n| dvs >> n & 1 == 1)
        .map(|n| DV_NAMES[n])
        .collect();
    names.join(" | ")
}

/// One vector group: the checks that share a pair of loads.
pub type Group = Vec<(usize, String)>;

/// Only a continuous range can share one vector load.
pub fn lane_groups(f: &Family, width: usize) -> Vec<Group> {
    let mut runs: Vec<Group> = Vec::new();
    for &(i, dvs) in &f.members {
        match runs.last_mut() {
            Some(run) if run.last().unwrap().0 + 1 == i => run.push((i, dv_expr(dvs))),
            _ => runs.push(vec![(i, dv_expr(dvs))]),
        }
    }
    runs.iter()
        .flat_map(|r| r.chunks(width).map(<[_]>::to_vec))
        .collect()
}

/// Every lane group with its family. Both vector emitters read this list, so
/// they always agree.
pub fn all_groups(plan: &Plan, width: usize) -> Vec<(&Family, Group)> {
    let mut groups: Vec<_> = plan
        .families
        .iter()
        .flat_map(|f| lane_groups(f, width).into_iter().map(move |g| (f, g)))
        .collect();
    // Earliest-available first: a group's loads cannot issue until the
    // compression has produced the highest schedule word it reads, and every
    // later OR into the same accumulator waits behind it.
    groups.sort_by_key(|(f, g)| g[0].0 + f.offset + width - 1);
    groups
}

/// The highest `w` index any group reads, for the module comment.
///
/// The emitted `load` proves its own bound at compile time, so this is the
/// second line of defence rather than the only one. It fails here, naming the
/// table, rather than inside a generated `const` block.
pub fn highest_read(plan: &Plan, width: usize) -> usize {
    let high = all_groups(plan, width)
        .iter()
        .map(|(f, g)| g[0].0 + f.offset + width - 1)
        .max()
        .unwrap_or(0);
    assert!(
        high < SCHEDULE,
        "a group reads w[{high}], past the {SCHEDULE}-word schedule"
    );
    high
}

/// Lane initializers. A short group gets a mask that clears no bits, so the
/// group still fills one vector.
pub fn lanes(bits: &[&str], indent: &str, width: usize) -> String {
    use std::fmt::Write as _;
    let mut out = String::new();
    for i in 0..width {
        let value = bits.get(i).copied().unwrap_or("0");
        let _ = write!(out, "\n{indent}    {value},");
    }
    let _ = write!(out, "\n{indent}");
    out
}

/// A whole generated module: the check for one target, then the two halves
/// it calls.
pub fn module(name: &str, prefix: &str, tail: &str) -> String {
    let (what, feature) = match name {
        "scalar" => ("scalar form, for a target with no vector unit", None),
        "neon" => ("`aarch64` NEON form", Some("neon")),
        "sse2" => ("SSE2 form", Some("sse2")),
        "avx2" => ("AVX2 form", Some("avx2")),
        other => panic!("no module shape for {other}"),
    };

    const BODY: &str = r#"    let mask = prefix(w);

    // Every check only clears bits, so an empty mask settles the answer.
    if mask == 0 {
        return 0;
    }

    tail(w, mask)
}
"#;

    // `#[target_feature]` on a safe function makes the body safe code: the
    // intrinsics need no `unsafe`, and a caller that cannot prove the feature
    // still has to write one. What is left of the unsafety is in `load`.
    let check = match feature {
        None => format!(
            "/// Runs the whole check.\n#[inline(always)]\npub(super) fn check(w: &Schedule) -> u32 {{\n{BODY}"
        ),
        Some(f) => format!(
            "/// Runs the whole check. Requires `{f}`, so a caller that cannot\n/// prove the feature needs an `unsafe` block.\n#[target_feature(enable = \"{f}\")]\npub(super) fn check(w: &Schedule) -> u32 {{\n{BODY}"
        ),
    };

    format!(
        "//! The UBC check, {what}.\n\
         //!\n\
         //! @generated by `codegen/` — do not edit by hand. Edit the table in\n\
         //! `codegen/src/ubc.rs`, the solver in `codegen/src/solve.rs` or this\n\
         //! target's plan in `codegen/src/main.rs`, and re-run it.\n\
         \n\
         use crate::Schedule;\n\
         use crate::ubc_check::*;\n\
         {}\n\
         {check}\n{prefix}\n{tail}",
        preamble(name)
    )
}

/// The arch import and the loads, for one target.
///
/// Everything the generated body does with a raw pointer goes through here,
/// so a whole module has one `unsafe` block per load shape and none in the
/// hundreds of lines that follow.
fn preamble(name: &str) -> String {
    match name {
        "scalar" => String::new(),
        "neon" => format!(
            "\nuse core::arch::aarch64::*;\n{}{}",
            load(
                "neon",
                4,
                "uint32x4_t",
                "vld1q_u32(w.words().as_ptr().add(at))"
            ),
            SPLAT
        ),
        "sse2" => format!(
            "{X86_IMPORTS}{}",
            load(
                "sse2",
                4,
                "__m128i",
                "_mm_loadu_si128(w.words().as_ptr().add(at).cast())"
            )
        ),
        "avx2" => format!(
            "{X86_IMPORTS}{}",
            load(
                "avx2",
                8,
                "__m256i",
                "_mm256_loadu_si256(w.words().as_ptr().add(at).cast())"
            )
        ),
        other => panic!("no preamble for {other}"),
    }
}

const X86_IMPORTS: &str = r#"
#[cfg(target_arch = "x86")]
use core::arch::x86::*;
#[cfg(target_arch = "x86_64")]
use core::arch::x86_64::*;
"#;

/// NEON has no intrinsic that takes four lanes directly, so the DV bits go
/// through memory like the schedule words do.
const SPLAT: &str = r#"
/// The DV bits of a group, as a vector.
#[inline]
#[target_feature(enable = "neon")]
fn splat(bits: [u32; 4]) -> uint32x4_t {
    // SAFETY: `vld1q_u32` reads four words, the length of `bits`.
    unsafe { vld1q_u32(bits.as_ptr()) }
}
"#;

/// The one load a generated body uses.
///
/// `I` is a const parameter, so the bound is a compile error at the call site
/// rather than a promise in a comment, and it holds for every plan this
/// generator can emit rather than only the one committed.
fn load(feature: &str, width: usize, ty: &str, call: &str) -> String {
    format!(
        r#"
/// The {width} schedule words of steps `I..I + {width}`.
///
/// One load on either layout; [`Schedule::window`] says where it starts. A
/// mirrored one hands back its lanes in the other order, which each group's
/// DV bits are emitted to match.
#[inline]
#[target_feature(enable = "{feature}")]
fn load<const I: usize>(w: &Schedule) -> {ty} {{
    const {{ assert!(I + {width} <= {SCHEDULE}, "a group reads past the schedule") }}
    let at = Schedule::window(I, {width});
    // SAFETY: the const assert above proves the {width}-word window is in
    // bounds wherever this layout puts it, which is all this reads.
    unsafe {{ {call} }}
}}
"#
    )
}
