//! Reads upstream's rules off its C check, for the tests.
//!
//! `upstream/` is a git submodule of sha1collisiondetection, so git pins the
//! commit and checks its contents. `build.rs` compiles its `lib/ubc_check.c`
//! into this generator, which is not published, so no C reaches sha1dc or its
//! users. To move to a newer upstream, check out that commit in the
//! submodule and run the generator again.
//!
//! Upstream tested its own generated check the same way the tests here do:
//! against a plain per-DV list of conditions (`ubc_check_verify.c` in
//! sha1collisiondetection-tools), over many random schedules. This writes
//! such a list, but reads it off the C by running it, rather than from the
//! data the C was generated from:
//!
//! - For each DV, it draws random schedules until upstream has kept the DV
//!   [`SAMPLES`] times. The bits whose flip rules the DV out, on the first of
//!   them, are the bits its conditions read.
//! - Those bits that always agree, or always disagree, across the samples are
//!   tied. Each tied group becomes rules: bit `u` XOR bit `v` must be `c`.
//! - It then checks the rules against the C, and writes nothing if they
//!   differ: on the first sample with each bit flipped, each group flipped
//!   whole, and each part of each group flipped, and on [`RANDOM`] random
//!   schedules.
//!
//! It writes them, and upstream's DV table, to `src/ubc_check/upstream.rs`,
//! next to the forms, and the tests in `src/ubc_check.rs` compare every form
//! against them. `--check` runs all of this again, so CI fails when the file
//! is stale.

use std::fmt::Write as _;

/// How many schedules upstream must keep each DV on before its bits are
/// grouped. Two bits that are not tied agree on all of them only by a chance
/// of one in 2^63, and the checks below would catch that too.
const SAMPLES: usize = 64;

/// How many random schedules the rules must give upstream's mask on.
const RANDOM: usize = 1_000_000;

/// `dv_info_t` of `ubc_check.h`.
#[repr(C)]
struct DvInfo {
    dv_type: i32,
    dv_k: i32,
    dv_b: i32,
    testt: i32,
    maski: i32,
    maskb: i32,
    dm: [u32; 80],
}

mod ffi {
    unsafe extern "C" {
        pub fn ubc_check(w: *const u32, dvmask: *mut u32);
        /// 32 DVs and an all-zero entry that ends the list.
        pub static sha1_dvs: [super::DvInfo; 33];
    }
}

/// Runs upstream's check over a schedule in step order.
fn ubc_check(w: &[u32; 80]) -> u32 {
    let mut mask = 0;
    // SAFETY: the C reads the 80 words of `w` and writes the one of `mask`.
    unsafe { ffi::ubc_check(w.as_ptr(), &mut mask) };
    mask
}

fn xorshift(seed: &mut u64) -> u64 {
    *seed ^= *seed << 13;
    *seed ^= *seed >> 7;
    *seed ^= *seed << 17;
    *seed
}

/// Bit `k` of a schedule: bit `k % 32` of word `k / 32`.
fn bit(w: &[u32; 80], k: usize) -> u32 {
    w[k / 32] >> (k % 32) & 1
}

fn flip(w: &[u32; 80], bits: &[usize]) -> [u32; 80] {
    let mut v = *w;
    for &k in bits {
        v[k / 32] ^= 1 << (k % 32);
    }
    v
}

/// One rule: for DV `dv`, bit `u` XOR bit `v` must be `c`.
struct Rule {
    dv: usize,
    u: usize,
    v: usize,
    c: u32,
}

/// The mask the rules give: a DV survives exactly where all its rules hold.
fn rules_mask(rules: &[Rule], w: &[u32; 80]) -> u32 {
    rules.iter().fold(!0, |mask, r| {
        if bit(w, r.u) ^ bit(w, r.v) == r.c {
            mask
        } else {
            mask & !(1 << r.dv)
        }
    })
}

/// Every part of `group` flipped on its own: each nonempty proper subset,
/// once per pair of complements, since flipping one or the other is the same
/// to every rule.
fn parts(group: &[usize]) -> Vec<Vec<usize>> {
    (1..1u32 << (group.len() - 1))
        .map(|set| {
            let mut part = vec![group[0]];
            part.extend(
                (1..group.len())
                    .filter(|&k| set >> (k - 1) & 1 == 0)
                    .map(|k| group[k]),
            );
            part
        })
        .collect()
}

/// FNV-1a over the little-endian bytes of `dm`. The tests hash sha1dc's own
/// differences the same way, so the file need not carry 2,560 words.
fn dm_hash(dm: &[u32; 80]) -> u64 {
    let mut hash = 0xcbf2_9ce4_8422_2325u64;
    for byte in dm.iter().flat_map(|w| w.to_le_bytes()) {
        hash ^= u64::from(byte);
        hash = hash.wrapping_mul(0x100_0000_01b3);
    }
    hash
}

/// `src/ubc_check/upstream.rs`: upstream's DV table and its rules, read off
/// the C and checked against it.
pub fn emit() -> String {
    let mut out = String::from(
        "//! Upstream's UBC check as rules, read off its C source by running it.\n\
         //!\n\
         //! @generated by `codegen/` from `lib/ubc_check.c` of sha1collisiondetection,\n\
         //! at the commit the submodule `codegen/upstream` pins. Do not edit by hand.\n\
         //! See `codegen/src/upstream.rs` for how.\n\
         \n\
         /// Upstream's DV table: type, K, B, `testt`, `maski`, `maskb`, and an\n\
         /// FNV-1a hash of the little-endian bytes of `dm`.\n",
    );

    // SAFETY: upstream defines these 33 entries, and nothing writes them.
    let dvs = unsafe { &*core::ptr::addr_of!(ffi::sha1_dvs) };
    assert_eq!(dvs[32].dv_type, 0, "upstream lists more than 32 DVs");
    let _ = writeln!(
        out,
        "pub(super) const DVS: [(i32, i32, i32, i32, i32, i32, u64); 32] = ["
    );
    for dv in &dvs[..32] {
        let _ = writeln!(
            out,
            "    ({}, {}, {}, {}, {}, {}, {:#018x}),",
            dv.dv_type,
            dv.dv_k,
            dv.dv_b,
            dv.testt,
            dv.maski,
            dv.maskb,
            dm_hash(&dv.dm)
        );
    }
    out.push_str("];\n");

    // Random schedules until upstream has kept every DV `SAMPLES` times. A
    // random schedule keeps a given DV between once in 128 and once in about
    // 50,000 tries.
    let mut seed = 0x243f_6a88_85a3_08d3u64;
    let mut kept: Vec<Vec<[u32; 80]>> = vec![Vec::new(); 32];
    while kept.iter().any(|k| k.len() < SAMPLES) {
        let w: [u32; 80] = core::array::from_fn(|_| xorshift(&mut seed) as u32);
        let mask = ubc_check(&w);
        for (dv, samples) in kept.iter_mut().enumerate() {
            if mask >> dv & 1 == 1 && samples.len() < SAMPLES {
                samples.push(w);
            }
        }
    }

    let mut rules = Vec::new();
    let mut groups: Vec<Vec<Vec<usize>>> = Vec::new();
    for (dv, samples) in kept.iter().enumerate() {
        let base = &samples[0];
        let read: Vec<usize> = (0..80 * 32)
            .filter(|&k| ubc_check(&flip(base, &[k])) >> dv & 1 == 0)
            .collect();

        let mut dv_groups: Vec<Vec<usize>> = Vec::new();
        for &u in &read {
            if dv_groups.iter().any(|g| g.contains(&u)) {
                continue;
            }
            let group: Vec<usize> = read
                .iter()
                .copied()
                .filter(|&v| {
                    let first = bit(&samples[0], u) ^ bit(&samples[0], v);
                    samples.iter().all(|s| bit(s, u) ^ bit(s, v) == first)
                })
                .collect();
            for &v in &group[1..] {
                rules.push(Rule {
                    dv,
                    u,
                    v,
                    c: bit(base, u) ^ bit(base, v),
                });
            }
            dv_groups.push(group);
        }
        groups.push(dv_groups);
    }

    // The rules must say what upstream says, next to each DV's block...
    for (dv, samples) in kept.iter().enumerate() {
        let base = &samples[0];
        let mut tried = vec![*base];
        tried.extend((0..80 * 32).map(|k| flip(base, &[k])));
        for group in &groups[dv] {
            tried.push(flip(base, group));
            tried.extend(parts(group).iter().map(|part| flip(base, part)));
        }
        for w in &tried {
            assert_eq!(
                rules_mask(&rules, w),
                ubc_check(w),
                "the rules read off upstream differ from it near DV {dv}"
            );
        }
    }

    // ...and on random schedules, expanded from messages as upstream's own
    // test draws them.
    let mut seed = 0x1319_8a2e_0370_7344u64;
    for _ in 0..RANDOM {
        let mut w = [0u32; 80];
        for word in w.iter_mut().take(16) {
            *word = xorshift(&mut seed) as u32;
        }
        for t in 16..80 {
            w[t] = (w[t - 3] ^ w[t - 8] ^ w[t - 14] ^ w[t - 16]).rotate_left(1);
        }
        assert_eq!(
            rules_mask(&rules, &w),
            ubc_check(&w),
            "the rules read off upstream differ from it on a random schedule"
        );
    }

    let _ = write!(
        out,
        "\n/// Upstream's rules: for DV `.0`, bit `.1` XOR bit `.2` must be `.3`.\n\
         /// Bit `k` is bit `k % 32` of step `k / 32`. A DV survives exactly where\n\
         /// all its rules hold. Its rules that share their `.1` tie one group of\n\
         /// bits to its first.\n\
         pub(super) const RULES: [(u8, u16, u16, u8); {}] = [\n",
        rules.len()
    );
    for r in &rules {
        let _ = writeln!(out, "    ({}, {}, {}, {}),", r.dv, r.u, r.v, r.c);
    }
    out.push_str("];\n");
    out
}
