//! The UBC check, `aarch64` NEON form.
//!
//! @generated by `codegen/` — do not edit by hand. Edit the table in
//! `codegen/src/ubc.rs`, the solver in `codegen/src/solve.rs` or this
//! target's plan in `codegen/src/main.rs`, and re-run it.

use crate::Schedule;
use crate::ubc_check::*;

use core::arch::aarch64::*;

/// The 4 schedule words of steps `I..I + 4`.
///
/// One load on either layout; [`Schedule::window`] says where it starts. A
/// mirrored one hands back its lanes in the other order, which each group's
/// DV bits are emitted to match.
#[inline]
#[target_feature(enable = "neon")]
fn load<const I: usize>(w: &Schedule) -> uint32x4_t {
    const { assert!(I + 4 <= 80, "a group reads past the schedule") }
    let at = Schedule::window(I, 4);
    // SAFETY: the const assert above proves the 4-word window is in
    // bounds wherever this layout puts it, which is all this reads.
    unsafe { vld1q_u32(w.words().as_ptr().add(at)) }
}

/// The DV bits of a group, as a vector.
#[inline]
#[target_feature(enable = "neon")]
fn splat(bits: [u32; 4]) -> uint32x4_t {
    // SAFETY: `vld1q_u32` reads four words, the length of `bits`.
    unsafe { vld1q_u32(bits.as_ptr()) }
}

/// Runs the whole check. Requires `neon`, so a caller that cannot
/// prove the feature needs an `unsafe` block.
#[target_feature(enable = "neon")]
pub(super) fn check(w: &Schedule) -> u32 {
    let mask = prefix(w);

    // Every check only clears bits, so an empty mask settles the answer.
    if mask == 0 {
        return 0;
    }

    tail(w, mask)
}

/// The checks that run on every block. Requires `neon`.
///
/// The highest index read is 56, and every load proves its own bound.
#[target_feature(enable = "neon")]
fn prefix(w: &Schedule) -> u32 {
    let mut acc0 = vdupq_n_u32(0);
    let mut acc1 = vdupq_n_u32(0);

    {
        let near = load::<35>(w);
        let far = load::<36>(w);
        let x = veorq_u32(near, vshrq_n_u32(far, 5));
        let hit = vceqq_u32(vandq_u32(x, vdupq_n_u32(1 << 1)), vdupq_n_u32(0));
        let bits = splat([
            DV_I_46_2_BIT | DV_I_49_2_BIT,
            DV_I_47_2_BIT | DV_I_50_2_BIT | DV_II_46_2_BIT,
            DV_I_48_2_BIT | DV_I_51_2_BIT,
            0,
        ]);
        acc0 = vorrq_u32(acc0, vandq_u32(hit, bits));
    }

    {
        let near = load::<36>(w);
        let far = load::<37>(w);
        let x = veorq_u32(near, vshrq_n_u32(far, 5));
        let hit = vceqq_u32(vandq_u32(x, vdupq_n_u32(1 << 0)), vdupq_n_u32(0));
        let bits = splat([DV_II_49_2_BIT, DV_II_50_2_BIT, DV_II_51_2_BIT, 0]);
        acc1 = vorrq_u32(acc1, vandq_u32(hit, bits));
    }

    {
        let near = load::<38>(w);
        let far = load::<39>(w);
        let x = veorq_u32(near, vshrq_n_u32(far, 5));
        let hit = vceqq_u32(vandq_u32(x, vdupq_n_u32(1 << 1)), vdupq_n_u32(0));
        let bits = splat([
            DV_I_49_2_BIT,
            DV_I_46_2_BIT | DV_I_50_2_BIT | DV_II_49_2_BIT,
            DV_I_47_2_BIT | DV_I_51_2_BIT | DV_II_50_2_BIT,
            DV_I_48_2_BIT | DV_II_46_2_BIT | DV_II_51_2_BIT,
        ]);
        acc0 = vorrq_u32(acc0, vandq_u32(hit, bits));
    }

    {
        let near = load::<39>(w);
        let far = load::<40>(w);
        let x = veorq_u32(vshrq_n_u32(near, 5), far);
        let hit = vtstq_u32(x, vdupq_n_u32(1 << 1));
        let bits = splat([
            DV_I_49_2_BIT,
            DV_I_50_2_BIT | DV_II_49_2_BIT,
            DV_I_51_2_BIT | DV_II_50_2_BIT,
            DV_II_46_2_BIT | DV_II_51_2_BIT,
        ]);
        acc1 = vorrq_u32(acc1, vandq_u32(hit, bits));
    }

    {
        let near = load::<39>(w);
        let far = load::<40>(w);
        let x = veorq_u32(near, vshrq_n_u32(far, 25));
        let hit = vceqq_u32(vandq_u32(x, vdupq_n_u32(1 << 4)), vdupq_n_u32(0));
        let bits = splat([
            DV_I_43_0_BIT | DV_II_53_0_BIT | DV_II_55_0_BIT,
            DV_I_44_0_BIT | DV_II_54_0_BIT | DV_II_56_0_BIT,
            DV_I_43_0_BIT | DV_I_45_0_BIT | DV_II_55_0_BIT,
            DV_I_44_0_BIT | DV_I_46_0_BIT | DV_II_56_0_BIT,
        ]);
        acc0 = vorrq_u32(acc0, vandq_u32(hit, bits));
    }

    {
        let near = load::<38>(w);
        let far = load::<41>(w);
        let x = veorq_u32(near, vshrq_n_u32(far, 25));
        let hit = vtstq_u32(x, vdupq_n_u32(1 << 4));
        let bits = splat([
            DV_I_44_0_BIT | DV_I_48_0_BIT | DV_II_47_0_BIT | DV_II_54_0_BIT | DV_II_56_0_BIT,
            DV_I_43_0_BIT | DV_I_45_0_BIT | DV_I_49_0_BIT | DV_II_48_0_BIT | DV_II_55_0_BIT,
            DV_I_44_0_BIT | DV_I_46_0_BIT | DV_I_50_0_BIT | DV_II_49_0_BIT | DV_II_56_0_BIT,
            DV_I_43_0_BIT
                | DV_I_45_0_BIT
                | DV_I_47_0_BIT
                | DV_I_51_0_BIT
                | DV_II_45_0_BIT
                | DV_II_50_0_BIT,
        ]);
        acc1 = vorrq_u32(acc1, vandq_u32(hit, bits));
    }

    {
        let near = load::<40>(w);
        let far = load::<41>(w);
        let x = veorq_u32(near, far);
        let hit = vtstq_u32(x, vdupq_n_u32(1 << 29));
        let bits = splat([
            DV_I_44_0_BIT
                | DV_I_47_0_BIT
                | DV_I_48_0_BIT
                | DV_II_46_0_BIT
                | DV_II_47_0_BIT
                | DV_II_56_0_BIT,
            DV_I_45_0_BIT | DV_I_48_0_BIT | DV_I_49_0_BIT | DV_II_47_0_BIT | DV_II_48_0_BIT,
            DV_I_46_0_BIT | DV_I_49_0_BIT | DV_I_50_0_BIT | DV_II_48_0_BIT | DV_II_49_0_BIT,
            DV_I_47_0_BIT
                | DV_I_50_0_BIT
                | DV_I_51_0_BIT
                | DV_II_45_0_BIT
                | DV_II_49_0_BIT
                | DV_II_50_0_BIT,
        ]);
        acc0 = vorrq_u32(acc0, vandq_u32(hit, bits));
    }

    {
        let near = load::<40>(w);
        let far = load::<43>(w);
        let x = veorq_u32(near, vshrq_n_u32(far, 25));
        let hit = vtstq_u32(x, vdupq_n_u32(1 << 4));
        let bits = splat([
            DV_I_44_0_BIT | DV_I_46_0_BIT | DV_I_50_0_BIT | DV_II_49_0_BIT | DV_II_56_0_BIT,
            DV_I_43_0_BIT
                | DV_I_45_0_BIT
                | DV_I_47_0_BIT
                | DV_I_51_0_BIT
                | DV_II_45_0_BIT
                | DV_II_50_0_BIT,
            DV_I_44_0_BIT
                | DV_I_46_0_BIT
                | DV_I_48_0_BIT
                | DV_I_52_0_BIT
                | DV_II_46_0_BIT
                | DV_II_51_0_BIT,
            DV_I_43_0_BIT
                | DV_I_45_0_BIT
                | DV_I_47_0_BIT
                | DV_I_49_0_BIT
                | DV_II_47_0_BIT
                | DV_II_52_0_BIT,
        ]);
        acc1 = vorrq_u32(acc1, vandq_u32(hit, bits));
    }

    {
        let near = load::<42>(w);
        let far = load::<44>(w);
        let x = veorq_u32(near, far);
        let hit = vtstq_u32(x, vdupq_n_u32(1 << 6));
        let bits = splat([
            DV_I_46_2_BIT | DV_I_48_2_BIT,
            DV_I_47_2_BIT | DV_I_49_2_BIT,
            DV_I_46_2_BIT | DV_I_48_2_BIT | DV_I_50_2_BIT,
            DV_I_47_2_BIT | DV_I_49_2_BIT | DV_I_51_2_BIT,
        ]);
        acc0 = vorrq_u32(acc0, vandq_u32(hit, bits));
    }

    {
        let near = load::<44>(w);
        let far = load::<45>(w);
        let x = veorq_u32(near, far);
        let hit = vtstq_u32(x, vdupq_n_u32(1 << 29));
        let bits = splat([
            DV_I_48_0_BIT
                | DV_I_51_0_BIT
                | DV_I_52_0_BIT
                | DV_II_45_0_BIT
                | DV_II_46_0_BIT
                | DV_II_50_0_BIT
                | DV_II_51_0_BIT,
            DV_I_49_0_BIT
                | DV_I_52_0_BIT
                | DV_II_46_0_BIT
                | DV_II_47_0_BIT
                | DV_II_51_0_BIT
                | DV_II_52_0_BIT,
            DV_I_43_0_BIT
                | DV_I_50_0_BIT
                | DV_II_47_0_BIT
                | DV_II_48_0_BIT
                | DV_II_52_0_BIT
                | DV_II_53_0_BIT,
            DV_I_44_0_BIT
                | DV_I_51_0_BIT
                | DV_II_48_0_BIT
                | DV_II_49_0_BIT
                | DV_II_53_0_BIT
                | DV_II_54_0_BIT,
        ]);
        acc1 = vorrq_u32(acc1, vandq_u32(hit, bits));
    }

    {
        let near = load::<44>(w);
        let far = load::<45>(w);
        let x = veorq_u32(near, vshrq_n_u32(far, 5));
        let hit = vceqq_u32(vandq_u32(x, vdupq_n_u32(1 << 1)), vdupq_n_u32(0));
        let bits = splat([
            DV_I_51_2_BIT | DV_II_49_2_BIT,
            DV_II_50_2_BIT,
            DV_II_51_2_BIT,
            DV_II_46_2_BIT,
        ]);
        acc0 = vorrq_u32(acc0, vandq_u32(hit, bits));
    }

    {
        let near = load::<45>(w);
        let far = load::<46>(w);
        let x = veorq_u32(vshrq_n_u32(near, 5), far);
        let hit = vtstq_u32(x, vdupq_n_u32(1 << 1));
        let bits = splat([
            DV_II_49_2_BIT,
            DV_I_46_2_BIT | DV_II_50_2_BIT,
            DV_I_47_2_BIT | DV_II_51_2_BIT,
            DV_I_48_2_BIT,
        ]);
        acc1 = vorrq_u32(acc1, vandq_u32(hit, bits));
    }

    {
        let near = load::<44>(w);
        let far = load::<47>(w);
        let x = veorq_u32(near, vshrq_n_u32(far, 25));
        let hit = vtstq_u32(x, vdupq_n_u32(1 << 4));
        let bits = splat([
            DV_I_44_0_BIT
                | DV_I_46_0_BIT
                | DV_I_48_0_BIT
                | DV_I_50_0_BIT
                | DV_II_48_0_BIT
                | DV_II_53_0_BIT,
            DV_I_45_0_BIT
                | DV_I_47_0_BIT
                | DV_I_49_0_BIT
                | DV_I_51_0_BIT
                | DV_II_49_0_BIT
                | DV_II_54_0_BIT,
            DV_I_46_0_BIT
                | DV_I_48_0_BIT
                | DV_I_50_0_BIT
                | DV_I_52_0_BIT
                | DV_II_50_0_BIT
                | DV_II_55_0_BIT,
            DV_I_47_0_BIT
                | DV_I_49_0_BIT
                | DV_I_51_0_BIT
                | DV_II_45_0_BIT
                | DV_II_51_0_BIT
                | DV_II_56_0_BIT,
        ]);
        acc0 = vorrq_u32(acc0, vandq_u32(hit, bits));
    }

    {
        let near = load::<46>(w);
        let far = load::<48>(w);
        let x = veorq_u32(near, far);
        let hit = vtstq_u32(x, vdupq_n_u32(1 << 6));
        let bits = splat([
            DV_I_48_2_BIT | DV_I_50_2_BIT,
            DV_I_49_2_BIT | DV_I_51_2_BIT,
            DV_I_50_2_BIT | DV_II_46_2_BIT,
            DV_I_51_2_BIT,
        ]);
        acc1 = vorrq_u32(acc1, vandq_u32(hit, bits));
    }

    {
        let near = load::<48>(w);
        let far = load::<49>(w);
        let x = veorq_u32(near, far);
        let hit = vtstq_u32(x, vdupq_n_u32(1 << 29));
        let bits = splat([
            DV_I_45_0_BIT
                | DV_I_52_0_BIT
                | DV_II_49_0_BIT
                | DV_II_50_0_BIT
                | DV_II_54_0_BIT
                | DV_II_55_0_BIT,
            DV_I_46_0_BIT
                | DV_II_45_0_BIT
                | DV_II_50_0_BIT
                | DV_II_51_0_BIT
                | DV_II_55_0_BIT
                | DV_II_56_0_BIT,
            DV_I_47_0_BIT | DV_II_46_0_BIT | DV_II_51_0_BIT | DV_II_52_0_BIT | DV_II_56_0_BIT,
            DV_I_48_0_BIT | DV_II_47_0_BIT | DV_II_52_0_BIT | DV_II_53_0_BIT,
        ]);
        acc0 = vorrq_u32(acc0, vandq_u32(hit, bits));
    }

    {
        let near = load::<48>(w);
        let far = load::<51>(w);
        let x = veorq_u32(near, vshrq_n_u32(far, 25));
        let hit = vtstq_u32(x, vdupq_n_u32(1 << 4));
        let bits = splat([
            DV_I_48_0_BIT | DV_I_50_0_BIT | DV_I_52_0_BIT | DV_II_46_0_BIT | DV_II_52_0_BIT,
            DV_I_49_0_BIT | DV_I_51_0_BIT | DV_II_45_0_BIT | DV_II_47_0_BIT | DV_II_53_0_BIT,
            DV_I_50_0_BIT | DV_I_52_0_BIT | DV_II_46_0_BIT | DV_II_48_0_BIT | DV_II_54_0_BIT,
            DV_I_51_0_BIT | DV_II_47_0_BIT | DV_II_49_0_BIT | DV_II_55_0_BIT,
        ]);
        acc1 = vorrq_u32(acc1, vandq_u32(hit, bits));
    }

    {
        let near = load::<52>(w);
        let far = load::<53>(w);
        let x = veorq_u32(near, far);
        let hit = vtstq_u32(x, vdupq_n_u32(1 << 29));
        let bits = splat([
            DV_I_49_0_BIT | DV_II_45_0_BIT | DV_II_48_0_BIT | DV_II_53_0_BIT | DV_II_54_0_BIT,
            DV_I_50_0_BIT | DV_II_46_0_BIT | DV_II_49_0_BIT | DV_II_54_0_BIT | DV_II_55_0_BIT,
            DV_I_51_0_BIT | DV_II_47_0_BIT | DV_II_50_0_BIT | DV_II_55_0_BIT | DV_II_56_0_BIT,
            DV_I_52_0_BIT | DV_II_48_0_BIT | DV_II_51_0_BIT | DV_II_56_0_BIT,
        ]);
        acc0 = vorrq_u32(acc0, vandq_u32(hit, bits));
    }

    let acc = vorrq_u32(acc0, acc1);
    let folded = vorr_u32(vget_low_u32(acc), vget_high_u32(acc));
    let cleared = vget_lane_u32(vorr_u32(folded, vdup_lane_u32(folded, 1)), 0);
    !cleared
}

/// The checks the prefix leaves. `mask` is never zero here.
#[inline(always)]
fn tail(w: &Schedule, mut mask: u32) -> u32 {
    if mask & (DV_I_43_0_BIT | DV_I_47_0_BIT | DV_II_46_0_BIT | DV_II_53_0_BIT | DV_II_55_0_BIT)
        != 0
    {
        mask &= (((w[37] >> 4) ^ (w[40] >> 29)) & 1).wrapping_sub(1)
            | !(DV_I_43_0_BIT | DV_I_47_0_BIT | DV_II_46_0_BIT | DV_II_53_0_BIT | DV_II_55_0_BIT);
    }
    if mask & (DV_I_46_0_BIT | DV_I_49_0_BIT | DV_II_45_0_BIT | DV_II_48_0_BIT) != 0 {
        mask &= (((w[36] >> 4) ^ (w[40] >> 29)) & 1).wrapping_sub(1)
            | !(DV_I_46_0_BIT | DV_I_49_0_BIT | DV_II_45_0_BIT | DV_II_48_0_BIT);
    }
    if mask & (DV_I_47_0_BIT | DV_I_50_0_BIT | DV_II_46_0_BIT | DV_II_49_0_BIT) != 0 {
        mask &= (((w[37] >> 4) ^ (w[41] >> 29)) & 1).wrapping_sub(1)
            | !(DV_I_47_0_BIT | DV_I_50_0_BIT | DV_II_46_0_BIT | DV_II_49_0_BIT);
    }
    if mask & (DV_I_48_0_BIT | DV_I_51_0_BIT | DV_II_47_0_BIT | DV_II_50_0_BIT) != 0 {
        mask &= (((w[38] >> 4) ^ (w[42] >> 29)) & 1).wrapping_sub(1)
            | !(DV_I_48_0_BIT | DV_I_51_0_BIT | DV_II_47_0_BIT | DV_II_50_0_BIT);
    }
    if mask & (DV_I_49_0_BIT | DV_I_52_0_BIT | DV_II_48_0_BIT | DV_II_51_0_BIT) != 0 {
        mask &= (((w[39] >> 4) ^ (w[43] >> 29)) & 1).wrapping_sub(1)
            | !(DV_I_49_0_BIT | DV_I_52_0_BIT | DV_II_48_0_BIT | DV_II_51_0_BIT);
    }
    if mask & (DV_I_51_0_BIT | DV_II_45_0_BIT | DV_II_50_0_BIT | DV_II_53_0_BIT) != 0 {
        mask &= (((w[41] >> 4) ^ (w[45] >> 29)) & 1).wrapping_sub(1)
            | !(DV_I_51_0_BIT | DV_II_45_0_BIT | DV_II_50_0_BIT | DV_II_53_0_BIT);
    }
    if mask & (DV_I_52_0_BIT | DV_II_46_0_BIT | DV_II_51_0_BIT | DV_II_54_0_BIT) != 0 {
        mask &= (((w[42] >> 4) ^ (w[46] >> 29)) & 1).wrapping_sub(1)
            | !(DV_I_52_0_BIT | DV_II_46_0_BIT | DV_II_51_0_BIT | DV_II_54_0_BIT);
    }
    if mask & (DV_I_43_0_BIT | DV_II_47_0_BIT | DV_II_52_0_BIT | DV_II_55_0_BIT) != 0 {
        mask &= (((w[43] >> 4) ^ (w[47] >> 29)) & 1).wrapping_sub(1)
            | !(DV_I_43_0_BIT | DV_II_47_0_BIT | DV_II_52_0_BIT | DV_II_55_0_BIT);
    }
    if mask & (DV_I_44_0_BIT | DV_II_48_0_BIT | DV_II_53_0_BIT | DV_II_56_0_BIT) != 0 {
        mask &= (((w[44] >> 4) ^ (w[48] >> 29)) & 1).wrapping_sub(1)
            | !(DV_I_44_0_BIT | DV_II_48_0_BIT | DV_II_53_0_BIT | DV_II_56_0_BIT);
    }
    if mask & (DV_I_52_0_BIT | DV_II_48_0_BIT | DV_II_50_0_BIT | DV_II_56_0_BIT) != 0 {
        mask &= (((w[52] >> 4) ^ (w[55] >> 29)) & 1).wrapping_sub(1)
            | !(DV_I_52_0_BIT | DV_II_48_0_BIT | DV_II_50_0_BIT | DV_II_56_0_BIT);
    }
    if mask & (DV_I_45_0_BIT | DV_I_48_0_BIT | DV_II_47_0_BIT) != 0 {
        mask &= (((w[35] >> 4) ^ (w[39] >> 29)) & 1).wrapping_sub(1)
            | !(DV_I_45_0_BIT | DV_I_48_0_BIT | DV_II_47_0_BIT);
    }
    if mask & (DV_I_50_0_BIT | DV_II_49_0_BIT | DV_II_52_0_BIT) != 0 {
        mask &= (((w[40] >> 4) ^ (w[44] >> 29)) & 1).wrapping_sub(1)
            | !(DV_I_50_0_BIT | DV_II_49_0_BIT | DV_II_52_0_BIT);
    }
    if mask & (DV_I_43_0_BIT | DV_I_45_0_BIT | DV_I_47_0_BIT) != 0 {
        mask &= (0u32).wrapping_sub(((w[41] >> 4) ^ (w[43] >> 4)) & 1)
            | !(DV_I_43_0_BIT | DV_I_45_0_BIT | DV_I_47_0_BIT);
    }
    if mask & (DV_I_44_0_BIT | DV_I_46_0_BIT | DV_I_48_0_BIT) != 0 {
        mask &= (0u32).wrapping_sub(((w[42] >> 4) ^ (w[44] >> 4)) & 1)
            | !(DV_I_44_0_BIT | DV_I_46_0_BIT | DV_I_48_0_BIT);
    }
    if mask & (DV_I_45_0_BIT | DV_I_47_0_BIT | DV_I_49_0_BIT) != 0 {
        mask &= (0u32).wrapping_sub(((w[43] >> 4) ^ (w[45] >> 4)) & 1)
            | !(DV_I_45_0_BIT | DV_I_47_0_BIT | DV_I_49_0_BIT);
    }
    if mask & (DV_I_46_0_BIT | DV_I_48_0_BIT | DV_I_50_0_BIT) != 0 {
        mask &= (0u32).wrapping_sub(((w[44] >> 4) ^ (w[46] >> 4)) & 1)
            | !(DV_I_46_0_BIT | DV_I_48_0_BIT | DV_I_50_0_BIT);
    }
    if mask & (DV_I_47_0_BIT | DV_I_49_0_BIT | DV_I_51_0_BIT) != 0 {
        mask &= (0u32).wrapping_sub(((w[45] >> 4) ^ (w[47] >> 4)) & 1)
            | !(DV_I_47_0_BIT | DV_I_49_0_BIT | DV_I_51_0_BIT);
    }
    if mask & (DV_I_48_0_BIT | DV_I_50_0_BIT | DV_I_52_0_BIT) != 0 {
        mask &= (0u32).wrapping_sub(((w[46] >> 4) ^ (w[48] >> 4)) & 1)
            | !(DV_I_48_0_BIT | DV_I_50_0_BIT | DV_I_52_0_BIT);
    }
    if mask & (DV_I_49_0_BIT | DV_I_51_0_BIT | DV_II_45_0_BIT) != 0 {
        mask &= (0u32).wrapping_sub(((w[47] >> 4) ^ (w[49] >> 4)) & 1)
            | !(DV_I_49_0_BIT | DV_I_51_0_BIT | DV_II_45_0_BIT);
    }
    if mask & (DV_I_50_0_BIT | DV_I_52_0_BIT | DV_II_46_0_BIT) != 0 {
        mask &= (0u32).wrapping_sub(((w[48] >> 4) ^ (w[50] >> 4)) & 1)
            | !(DV_I_50_0_BIT | DV_I_52_0_BIT | DV_II_46_0_BIT);
    }
    if mask & (DV_I_51_0_BIT | DV_II_47_0_BIT | DV_II_48_0_BIT) != 0 {
        mask &= (0u32).wrapping_sub(((w[52] >> 29) ^ (w[55] >> 29)) & 1)
            | !(DV_I_51_0_BIT | DV_II_47_0_BIT | DV_II_48_0_BIT);
    }
    if mask & (DV_I_52_0_BIT | DV_II_48_0_BIT | DV_II_49_0_BIT) != 0 {
        mask &= (0u32).wrapping_sub(((w[53] >> 29) ^ (w[56] >> 29)) & 1)
            | !(DV_I_52_0_BIT | DV_II_48_0_BIT | DV_II_49_0_BIT);
    }
    if mask & (DV_I_51_0_BIT | DV_II_47_0_BIT) != 0 {
        mask &= (((w[35] >> 3) ^ (w[39] >> 28)) & 1).wrapping_sub(1)
            | !(DV_I_51_0_BIT | DV_II_47_0_BIT);
    }
    if mask & (DV_II_52_0_BIT | DV_II_54_0_BIT) != 0 {
        mask &= (0u32).wrapping_sub(((w[36] >> 4) ^ (w[38] >> 4)) & 1)
            | !(DV_II_52_0_BIT | DV_II_54_0_BIT);
    }
    if mask & (DV_I_50_2_BIT | DV_II_46_2_BIT) != 0 {
        mask &=
            (((w[48] >> 6) ^ (w[51] >> 1)) & 1).wrapping_sub(1) | !(DV_I_50_2_BIT | DV_II_46_2_BIT);
    }
    if mask & (DV_II_49_0_BIT | DV_II_51_0_BIT) != 0 {
        mask &= (((w[53] >> 4) ^ (w[56] >> 29)) & 1).wrapping_sub(1)
            | !(DV_II_49_0_BIT | DV_II_51_0_BIT);
    }
    if mask & (DV_II_50_0_BIT | DV_II_52_0_BIT) != 0 {
        mask &= (((w[54] >> 4) ^ (w[57] >> 29)) & 1).wrapping_sub(1)
            | !(DV_II_50_0_BIT | DV_II_52_0_BIT);
    }
    if mask & (DV_II_49_0_BIT | DV_II_50_0_BIT) != 0 {
        mask &= (0u32).wrapping_sub(((w[54] >> 29) ^ (w[57] >> 29)) & 1)
            | !(DV_II_49_0_BIT | DV_II_50_0_BIT);
    }
    if mask & (DV_II_51_0_BIT | DV_II_53_0_BIT) != 0 {
        mask &= (((w[55] >> 4) ^ (w[58] >> 29)) & 1).wrapping_sub(1)
            | !(DV_II_51_0_BIT | DV_II_53_0_BIT);
    }
    if mask & (DV_II_50_0_BIT | DV_II_51_0_BIT) != 0 {
        mask &= (0u32).wrapping_sub(((w[55] >> 29) ^ (w[58] >> 29)) & 1)
            | !(DV_II_50_0_BIT | DV_II_51_0_BIT);
    }
    if mask & (DV_II_52_0_BIT | DV_II_54_0_BIT) != 0 {
        mask &= (((w[56] >> 4) ^ (w[59] >> 29)) & 1).wrapping_sub(1)
            | !(DV_II_52_0_BIT | DV_II_54_0_BIT);
    }
    if mask & (DV_II_51_0_BIT | DV_II_52_0_BIT) != 0 {
        mask &= (0u32).wrapping_sub(((w[56] >> 29) ^ (w[59] >> 29)) & 1)
            | !(DV_II_51_0_BIT | DV_II_52_0_BIT);
    }
    if mask & (DV_I_45_0_BIT | DV_II_45_0_BIT) != 0 {
        mask &= (0u32).wrapping_sub((w[60] ^ (w[61] >> 5)) & 1) | !(DV_I_45_0_BIT | DV_II_45_0_BIT);
    }
    if mask & (DV_I_46_0_BIT | DV_II_46_0_BIT) != 0 {
        mask &= (0u32).wrapping_sub((w[61] ^ (w[62] >> 5)) & 1) | !(DV_I_46_0_BIT | DV_II_46_0_BIT);
    }
    if mask & (DV_I_46_2_BIT | DV_II_46_2_BIT) != 0 {
        mask &= (0u32).wrapping_sub(((w[61] >> 2) ^ (w[62] >> 7)) & 1)
            | !(DV_I_46_2_BIT | DV_II_46_2_BIT);
    }
    if mask & (DV_I_47_0_BIT | DV_II_47_0_BIT) != 0 {
        mask &= (0u32).wrapping_sub((w[62] ^ (w[63] >> 5)) & 1) | !(DV_I_47_0_BIT | DV_II_47_0_BIT);
    }
    if mask & (DV_I_48_0_BIT | DV_II_48_0_BIT) != 0 {
        mask &= (0u32).wrapping_sub((w[63] ^ (w[64] >> 5)) & 1) | !(DV_I_48_0_BIT | DV_II_48_0_BIT);
    }
    if mask & (DV_I_45_0_BIT | DV_II_45_0_BIT) != 0 {
        mask &= (0u32).wrapping_sub(((w[63] >> 1) ^ (w[64] >> 6)) & 1)
            | !(DV_I_45_0_BIT | DV_II_45_0_BIT);
    }

    if mask == 0 {
        return 0;
    }

    if mask & (DV_I_43_0_BIT | DV_I_44_0_BIT | DV_I_46_2_BIT) != 0 {
        if mask & DV_I_43_0_BIT != 0
            && ((w[58] ^ (w[59] >> 5)) & 1 == 0
                || (w[58] ^ (w[63] >> 30)) & 1 == 0
                || ((w[61] >> 1) ^ (w[62] >> 6)) & 1 == 0)
        {
            mask &= !DV_I_43_0_BIT;
        }
        if mask & DV_I_44_0_BIT != 0
            && ((w[59] ^ (w[60] >> 5)) & 1 == 0
                || (w[59] ^ (w[64] >> 30)) & 1 == 0
                || ((w[62] >> 1) ^ (w[63] >> 6)) & 1 == 0)
        {
            mask &= !DV_I_44_0_BIT;
        }
        if mask & DV_I_46_2_BIT != 0 && ((w[39] >> 1) ^ (w[42] >> 6)) & 1 == 0 {
            mask &= !DV_I_46_2_BIT;
        }
    }

    if mask & (DV_I_47_2_BIT | DV_I_48_2_BIT | DV_I_49_2_BIT) != 0 {
        if mask & DV_I_47_2_BIT != 0
            && (((w[40] >> 1) ^ (w[43] >> 6)) & 1 == 0 || ((w[62] >> 2) ^ (w[63] >> 7)) & 1 == 0)
        {
            mask &= !DV_I_47_2_BIT;
        }
        if mask & DV_I_48_2_BIT != 0 && ((w[63] >> 2) ^ (w[64] >> 7)) & 1 == 0 {
            mask &= !DV_I_48_2_BIT;
        }
        if mask & DV_I_49_2_BIT != 0
            && (((w[42] >> 1) ^ (w[43] >> 6)) & 1 == 0 || ((w[42] >> 1) ^ (w[50] >> 1)) & 1 == 0)
        {
            mask &= !DV_I_49_2_BIT;
        }
    }

    if mask == 0 {
        return 0;
    }

    if mask & (DV_I_50_0_BIT | DV_I_50_2_BIT | DV_I_51_0_BIT) != 0 {
        if mask & DV_I_50_0_BIT != 0 && ((w[36] >> 4) ^ (w[37] >> 4)) & 1 == 0 {
            mask &= !DV_I_50_0_BIT;
        }
        if mask & DV_I_50_2_BIT != 0 && ((w[43] >> 1) ^ (w[44] >> 6)) & 1 == 0 {
            mask &= !DV_I_50_2_BIT;
        }
        if mask & DV_I_51_0_BIT != 0 && ((w[37] >> 4) ^ (w[38] >> 4)) & 1 == 0 {
            mask &= !DV_I_51_0_BIT;
        }
    }

    if mask & (DV_I_51_2_BIT | DV_I_52_0_BIT | DV_II_48_0_BIT) != 0 {
        if mask & DV_I_51_2_BIT != 0
            && (((w[35] >> 5) ^ (w[39] >> 30)) & 1 != 0
                || ((w[37] >> 1) ^ (w[37] >> 6)) & 1 != 0
                || ((w[44] >> 1) ^ (w[52] >> 1)) & 1 == 0)
        {
            mask &= !DV_I_51_2_BIT;
        }
        if mask & DV_I_52_0_BIT != 0 && ((w[38] >> 4) ^ (w[39] >> 4)) & 1 == 0 {
            mask &= !DV_I_52_0_BIT;
        }
        if mask & DV_II_48_0_BIT != 0
            && (((w[35] >> 30) ^ (w[36] >> 3)) & 1 == 0 || ((w[35] >> 30) ^ (w[40] >> 28)) & 1 == 0)
        {
            mask &= !DV_II_48_0_BIT;
        }
    }

    if mask == 0 {
        return 0;
    }

    if mask & (DV_II_49_0_BIT | DV_II_49_2_BIT | DV_II_50_0_BIT) != 0 {
        if mask & DV_II_49_0_BIT != 0
            && (((w[36] >> 30) ^ (w[37] >> 3)) & 1 == 0 || ((w[36] >> 30) ^ (w[41] >> 28)) & 1 == 0)
        {
            mask &= !DV_II_49_0_BIT;
        }
        if mask & DV_II_49_2_BIT != 0
            && ((w[36] ^ (w[41] >> 30)) & 1 == 0
                || ((w[50] >> 1) ^ (w[51] >> 6)) & 1 == 0
                || ((w[50] >> 1) ^ (w[53] >> 6)) & 1 == 0
                || ((w[50] >> 1) ^ (w[54] >> 1)) & 1 == 0)
        {
            mask &= !DV_II_49_2_BIT;
        }
        if mask & DV_II_50_0_BIT != 0
            && (((w[37] >> 30) ^ (w[38] >> 3)) & 1 == 0 || ((w[37] >> 30) ^ (w[42] >> 28)) & 1 == 0)
        {
            mask &= !DV_II_50_0_BIT;
        }
    }

    if mask & (DV_II_50_2_BIT | DV_II_51_0_BIT | DV_II_51_2_BIT) != 0 {
        if mask & DV_II_50_2_BIT != 0
            && ((w[37] ^ (w[42] >> 30)) & 1 == 0
                || ((w[51] >> 1) ^ (w[52] >> 6)) & 1 == 0
                || ((w[51] >> 1) ^ (w[54] >> 6)) & 1 == 0
                || ((w[51] >> 1) ^ (w[55] >> 1)) & 1 == 0)
        {
            mask &= !DV_II_50_2_BIT;
        }
        if mask & DV_II_51_0_BIT != 0
            && (((w[38] >> 30) ^ (w[39] >> 3)) & 1 == 0 || ((w[38] >> 30) ^ (w[43] >> 28)) & 1 == 0)
        {
            mask &= !DV_II_51_0_BIT;
        }
        if mask & DV_II_51_2_BIT != 0
            && ((w[38] ^ (w[43] >> 30)) & 1 == 0
                || ((w[52] >> 1) ^ (w[53] >> 6)) & 1 == 0
                || ((w[52] >> 1) ^ (w[55] >> 6)) & 1 == 0
                || ((w[52] >> 1) ^ (w[56] >> 1)) & 1 == 0)
        {
            mask &= !DV_II_51_2_BIT;
        }
    }

    if mask == 0 {
        return 0;
    }

    if mask & (DV_II_52_0_BIT | DV_II_53_0_BIT | DV_II_54_0_BIT) != 0 {
        if mask & DV_II_52_0_BIT != 0
            && (((w[39] >> 30) ^ (w[40] >> 3)) & 1 == 0
                || ((w[39] >> 30) ^ (w[44] >> 28)) & 1 == 0
                || ((w[54] >> 4) ^ (w[56] >> 4)) & 1 == 0
                || ((w[54] >> 4) ^ (w[60] >> 29)) & 1 == 0)
        {
            mask &= !DV_II_52_0_BIT;
        }
        if mask & DV_II_53_0_BIT != 0
            && (((w[41] >> 3) ^ (w[45] >> 28)) & 1 != 0
                || ((w[55] >> 4) ^ (w[57] >> 4)) & 1 == 0
                || ((w[55] >> 4) ^ (w[57] >> 29)) & 1 != 0
                || ((w[55] >> 4) ^ (w[61] >> 29)) & 1 == 0)
        {
            mask &= !DV_II_53_0_BIT;
        }
        if mask & DV_II_54_0_BIT != 0
            && (((w[42] >> 3) ^ (w[46] >> 28)) & 1 != 0
                || ((w[56] >> 4) ^ (w[58] >> 29)) & 1 != 0
                || ((w[58] >> 4) ^ (w[62] >> 29)) & 1 != 0)
        {
            mask &= !DV_II_54_0_BIT;
        }
    }

    if mask & (DV_II_55_0_BIT | DV_II_56_0_BIT) != 0 {
        if mask & DV_II_55_0_BIT != 0
            && (((w[43] >> 3) ^ (w[47] >> 28)) & 1 != 0
                || ((w[57] >> 4) ^ (w[59] >> 29)) & 1 != 0
                || ((w[59] >> 4) ^ (w[63] >> 29)) & 1 != 0)
        {
            mask &= !DV_II_55_0_BIT;
        }
        if mask & DV_II_56_0_BIT != 0
            && (((w[44] >> 3) ^ (w[48] >> 28)) & 1 != 0 || ((w[60] >> 4) ^ (w[64] >> 29)) & 1 != 0)
        {
            mask &= !DV_II_56_0_BIT;
        }
    }

    mask
}
