//! The UBC check, SSE2 form.
//!
//! @generated by `codegen/` — do not edit by hand. Edit the table in
//! `codegen/src/ubc.rs`, the solver in `codegen/src/solve.rs` or this
//! target's plan in `codegen/src/main.rs`, and re-run it.

use crate::ubc_check::*;

/// Runs the whole check.
///
/// # Safety
///
/// Requires `sse2`. All reads stay in `w`.
#[target_feature(enable = "sse2")]
#[allow(unsafe_op_in_unsafe_fn)]
pub(super) unsafe fn check(w: &[u32; 80]) -> u32 {
    let mask = prefix(w);

    // Every check only clears bits, so an empty mask settles the answer.
    if mask == 0 {
        return 0;
    }

    tail(w, mask)
}

/// # Safety
///
/// Requires `sse2`. Every load stays in `w`. The highest index read is 56.
#[target_feature(enable = "sse2")]
#[allow(unsafe_op_in_unsafe_fn)]
unsafe fn prefix(w: &[u32; 80]) -> u32 {
    #[cfg(target_arch = "x86")]
    use core::arch::x86::*;
    #[cfg(target_arch = "x86_64")]
    use core::arch::x86_64::*;

    let p = w.as_ptr();
    let zero = _mm_setzero_si128();
    let mut acc0 = zero;
    let mut acc1 = zero;

    {
        let near = _mm_loadu_si128(p.add(35).cast());
        let far = _mm_loadu_si128(p.add(36).cast());
        let x = _mm_xor_si128(near, _mm_srli_epi32(far, 5));
        let tested = _mm_and_si128(x, _mm_set1_epi32(1 << 1));
        let miss = _mm_cmpeq_epi32(tested, zero);
        let bits = _mm_setr_epi32(
            (DV_I_46_2_BIT | DV_I_49_2_BIT) as i32,
            (DV_I_47_2_BIT | DV_I_50_2_BIT | DV_II_46_2_BIT) as i32,
            (DV_I_48_2_BIT | DV_I_51_2_BIT) as i32,
            0,
        );
        acc0 = _mm_or_si128(acc0, _mm_and_si128(miss, bits));
    }

    {
        let near = _mm_loadu_si128(p.add(36).cast());
        let far = _mm_loadu_si128(p.add(37).cast());
        let x = _mm_xor_si128(near, _mm_srli_epi32(far, 5));
        let tested = _mm_and_si128(x, _mm_set1_epi32(1 << 0));
        let miss = _mm_cmpeq_epi32(tested, zero);
        let bits = _mm_setr_epi32(
            (DV_II_49_2_BIT) as i32,
            (DV_II_50_2_BIT) as i32,
            (DV_II_51_2_BIT) as i32,
            0,
        );
        acc1 = _mm_or_si128(acc1, _mm_and_si128(miss, bits));
    }

    {
        let near = _mm_loadu_si128(p.add(38).cast());
        let far = _mm_loadu_si128(p.add(39).cast());
        let x = _mm_xor_si128(near, _mm_srli_epi32(far, 5));
        let tested = _mm_and_si128(x, _mm_set1_epi32(1 << 1));
        let miss = _mm_cmpeq_epi32(tested, zero);
        let bits = _mm_setr_epi32(
            (DV_I_49_2_BIT) as i32,
            (DV_I_46_2_BIT | DV_I_50_2_BIT | DV_II_49_2_BIT) as i32,
            (DV_I_47_2_BIT | DV_I_51_2_BIT | DV_II_50_2_BIT) as i32,
            (DV_I_48_2_BIT | DV_II_46_2_BIT | DV_II_51_2_BIT) as i32,
        );
        acc0 = _mm_or_si128(acc0, _mm_and_si128(miss, bits));
    }

    {
        let near = _mm_loadu_si128(p.add(39).cast());
        let far = _mm_loadu_si128(p.add(40).cast());
        let x = _mm_xor_si128(_mm_srli_epi32(near, 5), far);
        let tested = _mm_and_si128(x, _mm_set1_epi32(1 << 1));
        let miss = _mm_cmpeq_epi32(tested, zero);
        let bits = _mm_setr_epi32(
            (DV_I_49_2_BIT) as i32,
            (DV_I_50_2_BIT | DV_II_49_2_BIT) as i32,
            (DV_I_51_2_BIT | DV_II_50_2_BIT) as i32,
            (DV_II_46_2_BIT | DV_II_51_2_BIT) as i32,
        );
        acc1 = _mm_or_si128(acc1, _mm_andnot_si128(miss, bits));
    }

    {
        let near = _mm_loadu_si128(p.add(39).cast());
        let far = _mm_loadu_si128(p.add(40).cast());
        let x = _mm_xor_si128(near, _mm_srli_epi32(far, 25));
        let tested = _mm_and_si128(x, _mm_set1_epi32(1 << 4));
        let miss = _mm_cmpeq_epi32(tested, zero);
        let bits = _mm_setr_epi32(
            (DV_I_43_0_BIT | DV_II_53_0_BIT | DV_II_55_0_BIT) as i32,
            (DV_I_44_0_BIT | DV_II_54_0_BIT | DV_II_56_0_BIT) as i32,
            (DV_I_43_0_BIT | DV_I_45_0_BIT | DV_II_55_0_BIT) as i32,
            (DV_I_44_0_BIT | DV_I_46_0_BIT | DV_II_56_0_BIT) as i32,
        );
        acc0 = _mm_or_si128(acc0, _mm_and_si128(miss, bits));
    }

    {
        let near = _mm_loadu_si128(p.add(38).cast());
        let far = _mm_loadu_si128(p.add(41).cast());
        let x = _mm_xor_si128(near, _mm_srli_epi32(far, 25));
        let tested = _mm_and_si128(x, _mm_set1_epi32(1 << 4));
        let miss = _mm_cmpeq_epi32(tested, zero);
        let bits = _mm_setr_epi32(
            (DV_I_44_0_BIT | DV_I_48_0_BIT | DV_II_47_0_BIT | DV_II_54_0_BIT | DV_II_56_0_BIT)
                as i32,
            (DV_I_43_0_BIT | DV_I_45_0_BIT | DV_I_49_0_BIT | DV_II_48_0_BIT | DV_II_55_0_BIT)
                as i32,
            (DV_I_44_0_BIT | DV_I_46_0_BIT | DV_I_50_0_BIT | DV_II_49_0_BIT | DV_II_56_0_BIT)
                as i32,
            (DV_I_43_0_BIT
                | DV_I_45_0_BIT
                | DV_I_47_0_BIT
                | DV_I_51_0_BIT
                | DV_II_45_0_BIT
                | DV_II_50_0_BIT) as i32,
        );
        acc1 = _mm_or_si128(acc1, _mm_andnot_si128(miss, bits));
    }

    {
        let near = _mm_loadu_si128(p.add(40).cast());
        let far = _mm_loadu_si128(p.add(41).cast());
        let x = _mm_xor_si128(near, far);
        let tested = _mm_and_si128(x, _mm_set1_epi32(1 << 29));
        let miss = _mm_cmpeq_epi32(tested, zero);
        let bits = _mm_setr_epi32(
            (DV_I_44_0_BIT
                | DV_I_47_0_BIT
                | DV_I_48_0_BIT
                | DV_II_46_0_BIT
                | DV_II_47_0_BIT
                | DV_II_56_0_BIT) as i32,
            (DV_I_45_0_BIT | DV_I_48_0_BIT | DV_I_49_0_BIT | DV_II_47_0_BIT | DV_II_48_0_BIT)
                as i32,
            (DV_I_46_0_BIT | DV_I_49_0_BIT | DV_I_50_0_BIT | DV_II_48_0_BIT | DV_II_49_0_BIT)
                as i32,
            (DV_I_47_0_BIT
                | DV_I_50_0_BIT
                | DV_I_51_0_BIT
                | DV_II_45_0_BIT
                | DV_II_49_0_BIT
                | DV_II_50_0_BIT) as i32,
        );
        acc0 = _mm_or_si128(acc0, _mm_andnot_si128(miss, bits));
    }

    {
        let near = _mm_loadu_si128(p.add(40).cast());
        let far = _mm_loadu_si128(p.add(43).cast());
        let x = _mm_xor_si128(near, _mm_srli_epi32(far, 25));
        let tested = _mm_and_si128(x, _mm_set1_epi32(1 << 4));
        let miss = _mm_cmpeq_epi32(tested, zero);
        let bits = _mm_setr_epi32(
            (DV_I_44_0_BIT | DV_I_46_0_BIT | DV_I_50_0_BIT | DV_II_49_0_BIT | DV_II_56_0_BIT)
                as i32,
            (DV_I_43_0_BIT
                | DV_I_45_0_BIT
                | DV_I_47_0_BIT
                | DV_I_51_0_BIT
                | DV_II_45_0_BIT
                | DV_II_50_0_BIT) as i32,
            (DV_I_44_0_BIT
                | DV_I_46_0_BIT
                | DV_I_48_0_BIT
                | DV_I_52_0_BIT
                | DV_II_46_0_BIT
                | DV_II_51_0_BIT) as i32,
            (DV_I_43_0_BIT
                | DV_I_45_0_BIT
                | DV_I_47_0_BIT
                | DV_I_49_0_BIT
                | DV_II_47_0_BIT
                | DV_II_52_0_BIT) as i32,
        );
        acc1 = _mm_or_si128(acc1, _mm_andnot_si128(miss, bits));
    }

    {
        let near = _mm_loadu_si128(p.add(42).cast());
        let far = _mm_loadu_si128(p.add(44).cast());
        let x = _mm_xor_si128(near, far);
        let tested = _mm_and_si128(x, _mm_set1_epi32(1 << 6));
        let miss = _mm_cmpeq_epi32(tested, zero);
        let bits = _mm_setr_epi32(
            (DV_I_46_2_BIT | DV_I_48_2_BIT) as i32,
            (DV_I_47_2_BIT | DV_I_49_2_BIT) as i32,
            (DV_I_46_2_BIT | DV_I_48_2_BIT | DV_I_50_2_BIT) as i32,
            (DV_I_47_2_BIT | DV_I_49_2_BIT | DV_I_51_2_BIT) as i32,
        );
        acc0 = _mm_or_si128(acc0, _mm_andnot_si128(miss, bits));
    }

    {
        let near = _mm_loadu_si128(p.add(44).cast());
        let far = _mm_loadu_si128(p.add(45).cast());
        let x = _mm_xor_si128(near, far);
        let tested = _mm_and_si128(x, _mm_set1_epi32(1 << 29));
        let miss = _mm_cmpeq_epi32(tested, zero);
        let bits = _mm_setr_epi32(
            (DV_I_48_0_BIT
                | DV_I_51_0_BIT
                | DV_I_52_0_BIT
                | DV_II_45_0_BIT
                | DV_II_46_0_BIT
                | DV_II_50_0_BIT
                | DV_II_51_0_BIT) as i32,
            (DV_I_49_0_BIT
                | DV_I_52_0_BIT
                | DV_II_46_0_BIT
                | DV_II_47_0_BIT
                | DV_II_51_0_BIT
                | DV_II_52_0_BIT) as i32,
            (DV_I_43_0_BIT
                | DV_I_50_0_BIT
                | DV_II_47_0_BIT
                | DV_II_48_0_BIT
                | DV_II_52_0_BIT
                | DV_II_53_0_BIT) as i32,
            (DV_I_44_0_BIT
                | DV_I_51_0_BIT
                | DV_II_48_0_BIT
                | DV_II_49_0_BIT
                | DV_II_53_0_BIT
                | DV_II_54_0_BIT) as i32,
        );
        acc1 = _mm_or_si128(acc1, _mm_andnot_si128(miss, bits));
    }

    {
        let near = _mm_loadu_si128(p.add(44).cast());
        let far = _mm_loadu_si128(p.add(45).cast());
        let x = _mm_xor_si128(near, _mm_srli_epi32(far, 5));
        let tested = _mm_and_si128(x, _mm_set1_epi32(1 << 1));
        let miss = _mm_cmpeq_epi32(tested, zero);
        let bits = _mm_setr_epi32(
            (DV_I_51_2_BIT | DV_II_49_2_BIT) as i32,
            (DV_II_50_2_BIT) as i32,
            (DV_II_51_2_BIT) as i32,
            (DV_II_46_2_BIT) as i32,
        );
        acc0 = _mm_or_si128(acc0, _mm_and_si128(miss, bits));
    }

    {
        let near = _mm_loadu_si128(p.add(45).cast());
        let far = _mm_loadu_si128(p.add(46).cast());
        let x = _mm_xor_si128(_mm_srli_epi32(near, 5), far);
        let tested = _mm_and_si128(x, _mm_set1_epi32(1 << 1));
        let miss = _mm_cmpeq_epi32(tested, zero);
        let bits = _mm_setr_epi32(
            (DV_II_49_2_BIT) as i32,
            (DV_I_46_2_BIT | DV_II_50_2_BIT) as i32,
            (DV_I_47_2_BIT | DV_II_51_2_BIT) as i32,
            (DV_I_48_2_BIT) as i32,
        );
        acc1 = _mm_or_si128(acc1, _mm_andnot_si128(miss, bits));
    }

    {
        let near = _mm_loadu_si128(p.add(44).cast());
        let far = _mm_loadu_si128(p.add(47).cast());
        let x = _mm_xor_si128(near, _mm_srli_epi32(far, 25));
        let tested = _mm_and_si128(x, _mm_set1_epi32(1 << 4));
        let miss = _mm_cmpeq_epi32(tested, zero);
        let bits = _mm_setr_epi32(
            (DV_I_44_0_BIT
                | DV_I_46_0_BIT
                | DV_I_48_0_BIT
                | DV_I_50_0_BIT
                | DV_II_48_0_BIT
                | DV_II_53_0_BIT) as i32,
            (DV_I_45_0_BIT
                | DV_I_47_0_BIT
                | DV_I_49_0_BIT
                | DV_I_51_0_BIT
                | DV_II_49_0_BIT
                | DV_II_54_0_BIT) as i32,
            (DV_I_46_0_BIT
                | DV_I_48_0_BIT
                | DV_I_50_0_BIT
                | DV_I_52_0_BIT
                | DV_II_50_0_BIT
                | DV_II_55_0_BIT) as i32,
            (DV_I_47_0_BIT
                | DV_I_49_0_BIT
                | DV_I_51_0_BIT
                | DV_II_45_0_BIT
                | DV_II_51_0_BIT
                | DV_II_56_0_BIT) as i32,
        );
        acc0 = _mm_or_si128(acc0, _mm_andnot_si128(miss, bits));
    }

    {
        let near = _mm_loadu_si128(p.add(46).cast());
        let far = _mm_loadu_si128(p.add(48).cast());
        let x = _mm_xor_si128(near, far);
        let tested = _mm_and_si128(x, _mm_set1_epi32(1 << 6));
        let miss = _mm_cmpeq_epi32(tested, zero);
        let bits = _mm_setr_epi32(
            (DV_I_48_2_BIT | DV_I_50_2_BIT) as i32,
            (DV_I_49_2_BIT | DV_I_51_2_BIT) as i32,
            (DV_I_50_2_BIT | DV_II_46_2_BIT) as i32,
            (DV_I_51_2_BIT) as i32,
        );
        acc1 = _mm_or_si128(acc1, _mm_andnot_si128(miss, bits));
    }

    {
        let near = _mm_loadu_si128(p.add(48).cast());
        let far = _mm_loadu_si128(p.add(49).cast());
        let x = _mm_xor_si128(near, far);
        let tested = _mm_and_si128(x, _mm_set1_epi32(1 << 29));
        let miss = _mm_cmpeq_epi32(tested, zero);
        let bits = _mm_setr_epi32(
            (DV_I_45_0_BIT
                | DV_I_52_0_BIT
                | DV_II_49_0_BIT
                | DV_II_50_0_BIT
                | DV_II_54_0_BIT
                | DV_II_55_0_BIT) as i32,
            (DV_I_46_0_BIT
                | DV_II_45_0_BIT
                | DV_II_50_0_BIT
                | DV_II_51_0_BIT
                | DV_II_55_0_BIT
                | DV_II_56_0_BIT) as i32,
            (DV_I_47_0_BIT | DV_II_46_0_BIT | DV_II_51_0_BIT | DV_II_52_0_BIT | DV_II_56_0_BIT)
                as i32,
            (DV_I_48_0_BIT | DV_II_47_0_BIT | DV_II_52_0_BIT | DV_II_53_0_BIT) as i32,
        );
        acc0 = _mm_or_si128(acc0, _mm_andnot_si128(miss, bits));
    }

    {
        let near = _mm_loadu_si128(p.add(48).cast());
        let far = _mm_loadu_si128(p.add(51).cast());
        let x = _mm_xor_si128(near, _mm_srli_epi32(far, 25));
        let tested = _mm_and_si128(x, _mm_set1_epi32(1 << 4));
        let miss = _mm_cmpeq_epi32(tested, zero);
        let bits = _mm_setr_epi32(
            (DV_I_48_0_BIT | DV_I_50_0_BIT | DV_I_52_0_BIT | DV_II_46_0_BIT | DV_II_52_0_BIT)
                as i32,
            (DV_I_49_0_BIT | DV_I_51_0_BIT | DV_II_45_0_BIT | DV_II_47_0_BIT | DV_II_53_0_BIT)
                as i32,
            (DV_I_50_0_BIT | DV_I_52_0_BIT | DV_II_46_0_BIT | DV_II_48_0_BIT | DV_II_54_0_BIT)
                as i32,
            (DV_I_51_0_BIT | DV_II_47_0_BIT | DV_II_49_0_BIT | DV_II_55_0_BIT) as i32,
        );
        acc1 = _mm_or_si128(acc1, _mm_andnot_si128(miss, bits));
    }

    {
        let near = _mm_loadu_si128(p.add(52).cast());
        let far = _mm_loadu_si128(p.add(53).cast());
        let x = _mm_xor_si128(near, far);
        let tested = _mm_and_si128(x, _mm_set1_epi32(1 << 29));
        let miss = _mm_cmpeq_epi32(tested, zero);
        let bits = _mm_setr_epi32(
            (DV_I_49_0_BIT | DV_II_45_0_BIT | DV_II_48_0_BIT | DV_II_53_0_BIT | DV_II_54_0_BIT)
                as i32,
            (DV_I_50_0_BIT | DV_II_46_0_BIT | DV_II_49_0_BIT | DV_II_54_0_BIT | DV_II_55_0_BIT)
                as i32,
            (DV_I_51_0_BIT | DV_II_47_0_BIT | DV_II_50_0_BIT | DV_II_55_0_BIT | DV_II_56_0_BIT)
                as i32,
            (DV_I_52_0_BIT | DV_II_48_0_BIT | DV_II_51_0_BIT | DV_II_56_0_BIT) as i32,
        );
        acc0 = _mm_or_si128(acc0, _mm_andnot_si128(miss, bits));
    }

    let acc = _mm_or_si128(acc0, acc1);
    let acc = _mm_or_si128(acc, _mm_shuffle_epi32(acc, 0b01_00_11_10));
    let acc = _mm_or_si128(acc, _mm_shuffle_epi32(acc, 0b10_11_00_01));
    !(_mm_cvtsi128_si32(acc) as u32)
}

/// The checks the prefix leaves. `mask` is never zero here.
#[inline(always)]
fn tail(w: &[u32; 80], mut mask: u32) -> u32 {
    if mask & (DV_I_43_0_BIT | DV_I_47_0_BIT | DV_II_46_0_BIT | DV_II_53_0_BIT | DV_II_55_0_BIT)
        != 0
    {
        mask &= (((w[37] >> 4) ^ (w[40] >> 29)) & 1).wrapping_sub(1)
            | !(DV_I_43_0_BIT | DV_I_47_0_BIT | DV_II_46_0_BIT | DV_II_53_0_BIT | DV_II_55_0_BIT);
    }
    if mask & (DV_I_46_0_BIT | DV_I_49_0_BIT | DV_II_45_0_BIT | DV_II_48_0_BIT) != 0 {
        mask &= (((w[36] >> 4) ^ (w[40] >> 29)) & 1).wrapping_sub(1)
            | !(DV_I_46_0_BIT | DV_I_49_0_BIT | DV_II_45_0_BIT | DV_II_48_0_BIT);
    }
    if mask & (DV_I_47_0_BIT | DV_I_50_0_BIT | DV_II_46_0_BIT | DV_II_49_0_BIT) != 0 {
        mask &= (((w[37] >> 4) ^ (w[41] >> 29)) & 1).wrapping_sub(1)
            | !(DV_I_47_0_BIT | DV_I_50_0_BIT | DV_II_46_0_BIT | DV_II_49_0_BIT);
    }
    if mask & (DV_I_48_0_BIT | DV_I_51_0_BIT | DV_II_47_0_BIT | DV_II_50_0_BIT) != 0 {
        mask &= (((w[38] >> 4) ^ (w[42] >> 29)) & 1).wrapping_sub(1)
            | !(DV_I_48_0_BIT | DV_I_51_0_BIT | DV_II_47_0_BIT | DV_II_50_0_BIT);
    }
    if mask & (DV_I_49_0_BIT | DV_I_52_0_BIT | DV_II_48_0_BIT | DV_II_51_0_BIT) != 0 {
        mask &= (((w[39] >> 4) ^ (w[43] >> 29)) & 1).wrapping_sub(1)
            | !(DV_I_49_0_BIT | DV_I_52_0_BIT | DV_II_48_0_BIT | DV_II_51_0_BIT);
    }
    if mask & (DV_I_51_0_BIT | DV_II_45_0_BIT | DV_II_50_0_BIT | DV_II_53_0_BIT) != 0 {
        mask &= (((w[41] >> 4) ^ (w[45] >> 29)) & 1).wrapping_sub(1)
            | !(DV_I_51_0_BIT | DV_II_45_0_BIT | DV_II_50_0_BIT | DV_II_53_0_BIT);
    }
    if mask & (DV_I_52_0_BIT | DV_II_46_0_BIT | DV_II_51_0_BIT | DV_II_54_0_BIT) != 0 {
        mask &= (((w[42] >> 4) ^ (w[46] >> 29)) & 1).wrapping_sub(1)
            | !(DV_I_52_0_BIT | DV_II_46_0_BIT | DV_II_51_0_BIT | DV_II_54_0_BIT);
    }
    if mask & (DV_I_43_0_BIT | DV_II_47_0_BIT | DV_II_52_0_BIT | DV_II_55_0_BIT) != 0 {
        mask &= (((w[43] >> 4) ^ (w[47] >> 29)) & 1).wrapping_sub(1)
            | !(DV_I_43_0_BIT | DV_II_47_0_BIT | DV_II_52_0_BIT | DV_II_55_0_BIT);
    }
    if mask & (DV_I_44_0_BIT | DV_II_48_0_BIT | DV_II_53_0_BIT | DV_II_56_0_BIT) != 0 {
        mask &= (((w[44] >> 4) ^ (w[48] >> 29)) & 1).wrapping_sub(1)
            | !(DV_I_44_0_BIT | DV_II_48_0_BIT | DV_II_53_0_BIT | DV_II_56_0_BIT);
    }
    if mask & (DV_I_52_0_BIT | DV_II_48_0_BIT | DV_II_50_0_BIT | DV_II_56_0_BIT) != 0 {
        mask &= (((w[52] >> 4) ^ (w[55] >> 29)) & 1).wrapping_sub(1)
            | !(DV_I_52_0_BIT | DV_II_48_0_BIT | DV_II_50_0_BIT | DV_II_56_0_BIT);
    }
    if mask & (DV_I_45_0_BIT | DV_I_48_0_BIT | DV_II_47_0_BIT) != 0 {
        mask &= (((w[35] >> 4) ^ (w[39] >> 29)) & 1).wrapping_sub(1)
            | !(DV_I_45_0_BIT | DV_I_48_0_BIT | DV_II_47_0_BIT);
    }
    if mask & (DV_I_50_0_BIT | DV_II_49_0_BIT | DV_II_52_0_BIT) != 0 {
        mask &= (((w[40] >> 4) ^ (w[44] >> 29)) & 1).wrapping_sub(1)
            | !(DV_I_50_0_BIT | DV_II_49_0_BIT | DV_II_52_0_BIT);
    }
    if mask & (DV_I_43_0_BIT | DV_I_45_0_BIT | DV_I_47_0_BIT) != 0 {
        mask &= (0u32).wrapping_sub(((w[41] >> 4) ^ (w[43] >> 4)) & 1)
            | !(DV_I_43_0_BIT | DV_I_45_0_BIT | DV_I_47_0_BIT);
    }
    if mask & (DV_I_44_0_BIT | DV_I_46_0_BIT | DV_I_48_0_BIT) != 0 {
        mask &= (0u32).wrapping_sub(((w[42] >> 4) ^ (w[44] >> 4)) & 1)
            | !(DV_I_44_0_BIT | DV_I_46_0_BIT | DV_I_48_0_BIT);
    }
    if mask & (DV_I_45_0_BIT | DV_I_47_0_BIT | DV_I_49_0_BIT) != 0 {
        mask &= (0u32).wrapping_sub(((w[43] >> 4) ^ (w[45] >> 4)) & 1)
            | !(DV_I_45_0_BIT | DV_I_47_0_BIT | DV_I_49_0_BIT);
    }
    if mask & (DV_I_46_0_BIT | DV_I_48_0_BIT | DV_I_50_0_BIT) != 0 {
        mask &= (0u32).wrapping_sub(((w[44] >> 4) ^ (w[46] >> 4)) & 1)
            | !(DV_I_46_0_BIT | DV_I_48_0_BIT | DV_I_50_0_BIT);
    }
    if mask & (DV_I_47_0_BIT | DV_I_49_0_BIT | DV_I_51_0_BIT) != 0 {
        mask &= (0u32).wrapping_sub(((w[45] >> 4) ^ (w[47] >> 4)) & 1)
            | !(DV_I_47_0_BIT | DV_I_49_0_BIT | DV_I_51_0_BIT);
    }
    if mask & (DV_I_48_0_BIT | DV_I_50_0_BIT | DV_I_52_0_BIT) != 0 {
        mask &= (0u32).wrapping_sub(((w[46] >> 4) ^ (w[48] >> 4)) & 1)
            | !(DV_I_48_0_BIT | DV_I_50_0_BIT | DV_I_52_0_BIT);
    }
    if mask & (DV_I_49_0_BIT | DV_I_51_0_BIT | DV_II_45_0_BIT) != 0 {
        mask &= (0u32).wrapping_sub(((w[47] >> 4) ^ (w[49] >> 4)) & 1)
            | !(DV_I_49_0_BIT | DV_I_51_0_BIT | DV_II_45_0_BIT);
    }
    if mask & (DV_I_50_0_BIT | DV_I_52_0_BIT | DV_II_46_0_BIT) != 0 {
        mask &= (0u32).wrapping_sub(((w[48] >> 4) ^ (w[50] >> 4)) & 1)
            | !(DV_I_50_0_BIT | DV_I_52_0_BIT | DV_II_46_0_BIT);
    }
    if mask & (DV_I_51_0_BIT | DV_II_47_0_BIT | DV_II_48_0_BIT) != 0 {
        mask &= (0u32).wrapping_sub(((w[52] >> 29) ^ (w[55] >> 29)) & 1)
            | !(DV_I_51_0_BIT | DV_II_47_0_BIT | DV_II_48_0_BIT);
    }
    if mask & (DV_I_52_0_BIT | DV_II_48_0_BIT | DV_II_49_0_BIT) != 0 {
        mask &= (0u32).wrapping_sub(((w[53] >> 29) ^ (w[56] >> 29)) & 1)
            | !(DV_I_52_0_BIT | DV_II_48_0_BIT | DV_II_49_0_BIT);
    }
    if mask & (DV_I_51_0_BIT | DV_II_47_0_BIT) != 0 {
        mask &= (((w[35] >> 3) ^ (w[39] >> 28)) & 1).wrapping_sub(1)
            | !(DV_I_51_0_BIT | DV_II_47_0_BIT);
    }
    if mask & (DV_II_52_0_BIT | DV_II_54_0_BIT) != 0 {
        mask &= (0u32).wrapping_sub(((w[36] >> 4) ^ (w[38] >> 4)) & 1)
            | !(DV_II_52_0_BIT | DV_II_54_0_BIT);
    }
    if mask & (DV_I_50_2_BIT | DV_II_46_2_BIT) != 0 {
        mask &=
            (((w[48] >> 6) ^ (w[51] >> 1)) & 1).wrapping_sub(1) | !(DV_I_50_2_BIT | DV_II_46_2_BIT);
    }
    if mask & (DV_II_49_0_BIT | DV_II_51_0_BIT) != 0 {
        mask &= (((w[53] >> 4) ^ (w[56] >> 29)) & 1).wrapping_sub(1)
            | !(DV_II_49_0_BIT | DV_II_51_0_BIT);
    }
    if mask & (DV_II_50_0_BIT | DV_II_52_0_BIT) != 0 {
        mask &= (((w[54] >> 4) ^ (w[57] >> 29)) & 1).wrapping_sub(1)
            | !(DV_II_50_0_BIT | DV_II_52_0_BIT);
    }
    if mask & (DV_II_49_0_BIT | DV_II_50_0_BIT) != 0 {
        mask &= (0u32).wrapping_sub(((w[54] >> 29) ^ (w[57] >> 29)) & 1)
            | !(DV_II_49_0_BIT | DV_II_50_0_BIT);
    }
    if mask & (DV_II_51_0_BIT | DV_II_53_0_BIT) != 0 {
        mask &= (((w[55] >> 4) ^ (w[58] >> 29)) & 1).wrapping_sub(1)
            | !(DV_II_51_0_BIT | DV_II_53_0_BIT);
    }
    if mask & (DV_II_50_0_BIT | DV_II_51_0_BIT) != 0 {
        mask &= (0u32).wrapping_sub(((w[55] >> 29) ^ (w[58] >> 29)) & 1)
            | !(DV_II_50_0_BIT | DV_II_51_0_BIT);
    }
    if mask & (DV_II_52_0_BIT | DV_II_54_0_BIT) != 0 {
        mask &= (((w[56] >> 4) ^ (w[59] >> 29)) & 1).wrapping_sub(1)
            | !(DV_II_52_0_BIT | DV_II_54_0_BIT);
    }
    if mask & (DV_II_51_0_BIT | DV_II_52_0_BIT) != 0 {
        mask &= (0u32).wrapping_sub(((w[56] >> 29) ^ (w[59] >> 29)) & 1)
            | !(DV_II_51_0_BIT | DV_II_52_0_BIT);
    }
    if mask & (DV_I_45_0_BIT | DV_II_45_0_BIT) != 0 {
        mask &= (0u32).wrapping_sub((w[60] ^ (w[61] >> 5)) & 1) | !(DV_I_45_0_BIT | DV_II_45_0_BIT);
    }
    if mask & (DV_I_46_0_BIT | DV_II_46_0_BIT) != 0 {
        mask &= (0u32).wrapping_sub((w[61] ^ (w[62] >> 5)) & 1) | !(DV_I_46_0_BIT | DV_II_46_0_BIT);
    }
    if mask & (DV_I_46_2_BIT | DV_II_46_2_BIT) != 0 {
        mask &= (0u32).wrapping_sub(((w[61] >> 2) ^ (w[62] >> 7)) & 1)
            | !(DV_I_46_2_BIT | DV_II_46_2_BIT);
    }
    if mask & (DV_I_47_0_BIT | DV_II_47_0_BIT) != 0 {
        mask &= (0u32).wrapping_sub((w[62] ^ (w[63] >> 5)) & 1) | !(DV_I_47_0_BIT | DV_II_47_0_BIT);
    }
    if mask & (DV_I_48_0_BIT | DV_II_48_0_BIT) != 0 {
        mask &= (0u32).wrapping_sub((w[63] ^ (w[64] >> 5)) & 1) | !(DV_I_48_0_BIT | DV_II_48_0_BIT);
    }
    if mask & (DV_I_45_0_BIT | DV_II_45_0_BIT) != 0 {
        mask &= (0u32).wrapping_sub(((w[63] >> 1) ^ (w[64] >> 6)) & 1)
            | !(DV_I_45_0_BIT | DV_II_45_0_BIT);
    }

    if mask == 0 {
        return 0;
    }

    if mask & (DV_I_43_0_BIT | DV_I_44_0_BIT | DV_I_46_2_BIT) != 0 {
        if mask & DV_I_43_0_BIT != 0
            && ((w[58] ^ (w[59] >> 5)) & 1 == 0
                || (w[58] ^ (w[63] >> 30)) & 1 == 0
                || ((w[61] >> 1) ^ (w[62] >> 6)) & 1 == 0)
        {
            mask &= !DV_I_43_0_BIT;
        }
        if mask & DV_I_44_0_BIT != 0
            && ((w[59] ^ (w[60] >> 5)) & 1 == 0
                || (w[59] ^ (w[64] >> 30)) & 1 == 0
                || ((w[62] >> 1) ^ (w[63] >> 6)) & 1 == 0)
        {
            mask &= !DV_I_44_0_BIT;
        }
        if mask & DV_I_46_2_BIT != 0 && ((w[39] >> 1) ^ (w[42] >> 6)) & 1 == 0 {
            mask &= !DV_I_46_2_BIT;
        }
    }

    if mask & (DV_I_47_2_BIT | DV_I_48_2_BIT | DV_I_49_2_BIT) != 0 {
        if mask & DV_I_47_2_BIT != 0
            && (((w[40] >> 1) ^ (w[43] >> 6)) & 1 == 0 || ((w[62] >> 2) ^ (w[63] >> 7)) & 1 == 0)
        {
            mask &= !DV_I_47_2_BIT;
        }
        if mask & DV_I_48_2_BIT != 0 && ((w[63] >> 2) ^ (w[64] >> 7)) & 1 == 0 {
            mask &= !DV_I_48_2_BIT;
        }
        if mask & DV_I_49_2_BIT != 0
            && (((w[42] >> 1) ^ (w[43] >> 6)) & 1 == 0 || ((w[42] >> 1) ^ (w[50] >> 1)) & 1 == 0)
        {
            mask &= !DV_I_49_2_BIT;
        }
    }

    if mask == 0 {
        return 0;
    }

    if mask & (DV_I_50_0_BIT | DV_I_50_2_BIT | DV_I_51_0_BIT) != 0 {
        if mask & DV_I_50_0_BIT != 0 && ((w[36] >> 4) ^ (w[37] >> 4)) & 1 == 0 {
            mask &= !DV_I_50_0_BIT;
        }
        if mask & DV_I_50_2_BIT != 0 && ((w[43] >> 1) ^ (w[44] >> 6)) & 1 == 0 {
            mask &= !DV_I_50_2_BIT;
        }
        if mask & DV_I_51_0_BIT != 0 && ((w[37] >> 4) ^ (w[38] >> 4)) & 1 == 0 {
            mask &= !DV_I_51_0_BIT;
        }
    }

    if mask & (DV_I_51_2_BIT | DV_I_52_0_BIT | DV_II_48_0_BIT) != 0 {
        if mask & DV_I_51_2_BIT != 0
            && (((w[35] >> 5) ^ (w[39] >> 30)) & 1 != 0
                || ((w[37] >> 1) ^ (w[37] >> 6)) & 1 != 0
                || ((w[44] >> 1) ^ (w[52] >> 1)) & 1 == 0)
        {
            mask &= !DV_I_51_2_BIT;
        }
        if mask & DV_I_52_0_BIT != 0 && ((w[38] >> 4) ^ (w[39] >> 4)) & 1 == 0 {
            mask &= !DV_I_52_0_BIT;
        }
        if mask & DV_II_48_0_BIT != 0
            && (((w[35] >> 30) ^ (w[36] >> 3)) & 1 == 0 || ((w[35] >> 30) ^ (w[40] >> 28)) & 1 == 0)
        {
            mask &= !DV_II_48_0_BIT;
        }
    }

    if mask == 0 {
        return 0;
    }

    if mask & (DV_II_49_0_BIT | DV_II_49_2_BIT | DV_II_50_0_BIT) != 0 {
        if mask & DV_II_49_0_BIT != 0
            && (((w[36] >> 30) ^ (w[37] >> 3)) & 1 == 0 || ((w[36] >> 30) ^ (w[41] >> 28)) & 1 == 0)
        {
            mask &= !DV_II_49_0_BIT;
        }
        if mask & DV_II_49_2_BIT != 0
            && ((w[36] ^ (w[41] >> 30)) & 1 == 0
                || ((w[50] >> 1) ^ (w[51] >> 6)) & 1 == 0
                || ((w[50] >> 1) ^ (w[53] >> 6)) & 1 == 0
                || ((w[50] >> 1) ^ (w[54] >> 1)) & 1 == 0)
        {
            mask &= !DV_II_49_2_BIT;
        }
        if mask & DV_II_50_0_BIT != 0
            && (((w[37] >> 30) ^ (w[38] >> 3)) & 1 == 0 || ((w[37] >> 30) ^ (w[42] >> 28)) & 1 == 0)
        {
            mask &= !DV_II_50_0_BIT;
        }
    }

    if mask & (DV_II_50_2_BIT | DV_II_51_0_BIT | DV_II_51_2_BIT) != 0 {
        if mask & DV_II_50_2_BIT != 0
            && ((w[37] ^ (w[42] >> 30)) & 1 == 0
                || ((w[51] >> 1) ^ (w[52] >> 6)) & 1 == 0
                || ((w[51] >> 1) ^ (w[54] >> 6)) & 1 == 0
                || ((w[51] >> 1) ^ (w[55] >> 1)) & 1 == 0)
        {
            mask &= !DV_II_50_2_BIT;
        }
        if mask & DV_II_51_0_BIT != 0
            && (((w[38] >> 30) ^ (w[39] >> 3)) & 1 == 0 || ((w[38] >> 30) ^ (w[43] >> 28)) & 1 == 0)
        {
            mask &= !DV_II_51_0_BIT;
        }
        if mask & DV_II_51_2_BIT != 0
            && ((w[38] ^ (w[43] >> 30)) & 1 == 0
                || ((w[52] >> 1) ^ (w[53] >> 6)) & 1 == 0
                || ((w[52] >> 1) ^ (w[55] >> 6)) & 1 == 0
                || ((w[52] >> 1) ^ (w[56] >> 1)) & 1 == 0)
        {
            mask &= !DV_II_51_2_BIT;
        }
    }

    if mask == 0 {
        return 0;
    }

    if mask & (DV_II_52_0_BIT | DV_II_53_0_BIT | DV_II_54_0_BIT) != 0 {
        if mask & DV_II_52_0_BIT != 0
            && (((w[39] >> 30) ^ (w[40] >> 3)) & 1 == 0
                || ((w[39] >> 30) ^ (w[44] >> 28)) & 1 == 0
                || ((w[54] >> 4) ^ (w[56] >> 4)) & 1 == 0
                || ((w[54] >> 4) ^ (w[60] >> 29)) & 1 == 0)
        {
            mask &= !DV_II_52_0_BIT;
        }
        if mask & DV_II_53_0_BIT != 0
            && (((w[41] >> 3) ^ (w[45] >> 28)) & 1 != 0
                || ((w[55] >> 4) ^ (w[57] >> 4)) & 1 == 0
                || ((w[55] >> 4) ^ (w[57] >> 29)) & 1 != 0
                || ((w[55] >> 4) ^ (w[61] >> 29)) & 1 == 0)
        {
            mask &= !DV_II_53_0_BIT;
        }
        if mask & DV_II_54_0_BIT != 0
            && (((w[42] >> 3) ^ (w[46] >> 28)) & 1 != 0
                || ((w[56] >> 4) ^ (w[58] >> 29)) & 1 != 0
                || ((w[58] >> 4) ^ (w[62] >> 29)) & 1 != 0)
        {
            mask &= !DV_II_54_0_BIT;
        }
    }

    if mask & (DV_II_55_0_BIT | DV_II_56_0_BIT) != 0 {
        if mask & DV_II_55_0_BIT != 0
            && (((w[43] >> 3) ^ (w[47] >> 28)) & 1 != 0
                || ((w[57] >> 4) ^ (w[59] >> 29)) & 1 != 0
                || ((w[59] >> 4) ^ (w[63] >> 29)) & 1 != 0)
        {
            mask &= !DV_II_55_0_BIT;
        }
        if mask & DV_II_56_0_BIT != 0
            && (((w[44] >> 3) ^ (w[48] >> 28)) & 1 != 0 || ((w[60] >> 4) ^ (w[64] >> 29)) & 1 != 0)
        {
            mask &= !DV_II_56_0_BIT;
        }
    }

    mask
}
