//! The UBC checks that the prefix leaves.
//!
//! @generated by `codegen/` — do not edit by hand. Edit the table in
//! `codegen/src/ubc.rs` or the solver in `codegen/src/solve.rs` and
//! re-run it.

use crate::ubc_check::*;

/// Clears the DVs that the remaining conditions rule out. The prefix has
/// already cleared what it covers, and `mask` is never zero here.
#[inline(always)]
pub(crate) fn mask(w: &[u32; 80], mut mask: u32) -> u32 {
    if mask & (DV_I_44_0_BIT | DV_I_48_0_BIT | DV_II_47_0_BIT | DV_II_56_0_BIT) != 0 {
        mask &= (((w[38] >> 4) ^ (w[40] >> 29)) & 1).wrapping_sub(1)
            | !(DV_I_44_0_BIT | DV_I_48_0_BIT | DV_II_47_0_BIT | DV_II_56_0_BIT);
    }
    if mask & (DV_I_43_0_BIT | DV_II_47_0_BIT | DV_II_52_0_BIT | DV_II_55_0_BIT) != 0 {
        mask &= (((w[43] >> 4) ^ (w[47] >> 29)) & 1).wrapping_sub(1)
            | !(DV_I_43_0_BIT | DV_II_47_0_BIT | DV_II_52_0_BIT | DV_II_55_0_BIT);
    }
    if mask & (DV_I_44_0_BIT | DV_II_48_0_BIT | DV_II_53_0_BIT | DV_II_56_0_BIT) != 0 {
        mask &= (((w[44] >> 4) ^ (w[48] >> 29)) & 1).wrapping_sub(1)
            | !(DV_I_44_0_BIT | DV_II_48_0_BIT | DV_II_53_0_BIT | DV_II_56_0_BIT);
    }
    if mask & (DV_I_45_0_BIT | DV_I_49_0_BIT | DV_II_48_0_BIT) != 0 {
        mask &= (((w[39] >> 4) ^ (w[41] >> 29)) & 1).wrapping_sub(1)
            | !(DV_I_45_0_BIT | DV_I_49_0_BIT | DV_II_48_0_BIT);
    }
    if mask & (DV_I_51_0_BIT | DV_II_47_0_BIT) != 0 {
        mask &= (((w[35] >> 3) ^ (w[39] >> 28)) & 1).wrapping_sub(1)
            | !(DV_I_51_0_BIT | DV_II_47_0_BIT);
    }
    if mask & (DV_II_52_0_BIT | DV_II_54_0_BIT) != 0 {
        mask &= (0u32).wrapping_sub(((w[36] >> 4) ^ (w[38] >> 4)) & 1)
            | !(DV_II_52_0_BIT | DV_II_54_0_BIT);
    }
    if mask & (DV_I_50_2_BIT | DV_II_49_2_BIT) != 0 {
        mask &= (0u32).wrapping_sub(((w[39] >> 1) ^ (w[41] >> 1)) & 1)
            | !(DV_I_50_2_BIT | DV_II_49_2_BIT);
    }
    if mask & (DV_I_51_2_BIT | DV_II_50_2_BIT) != 0 {
        mask &= (0u32).wrapping_sub(((w[40] >> 1) ^ (w[42] >> 1)) & 1)
            | !(DV_I_51_2_BIT | DV_II_50_2_BIT);
    }
    if mask & (DV_II_46_2_BIT | DV_II_51_2_BIT) != 0 {
        mask &= (0u32).wrapping_sub(((w[41] >> 1) ^ (w[43] >> 1)) & 1)
            | !(DV_II_46_2_BIT | DV_II_51_2_BIT);
    }
    if mask & (DV_I_51_2_BIT | DV_II_49_2_BIT) != 0 {
        mask &= (0u32).wrapping_sub(((w[44] >> 1) ^ (w[45] >> 6)) & 1)
            | !(DV_I_51_2_BIT | DV_II_49_2_BIT);
    }
    if mask & (DV_I_46_2_BIT | DV_II_50_2_BIT) != 0 {
        mask &=
            (((w[46] >> 6) ^ (w[47] >> 1)) & 1).wrapping_sub(1) | !(DV_I_46_2_BIT | DV_II_50_2_BIT);
    }
    if mask & (DV_I_47_2_BIT | DV_II_51_2_BIT) != 0 {
        mask &=
            (((w[47] >> 6) ^ (w[48] >> 1)) & 1).wrapping_sub(1) | !(DV_I_47_2_BIT | DV_II_51_2_BIT);
    }
    if mask & (DV_I_50_2_BIT | DV_II_46_2_BIT) != 0 {
        mask &=
            (((w[48] >> 6) ^ (w[51] >> 1)) & 1).wrapping_sub(1) | !(DV_I_50_2_BIT | DV_II_46_2_BIT);
    }
    if mask & (DV_II_52_0_BIT | DV_II_54_0_BIT) != 0 {
        mask &= (((w[56] >> 4) ^ (w[59] >> 29)) & 1).wrapping_sub(1)
            | !(DV_II_52_0_BIT | DV_II_54_0_BIT);
    }
    if mask & (DV_II_51_0_BIT | DV_II_52_0_BIT) != 0 {
        mask &= (0u32).wrapping_sub(((w[56] >> 29) ^ (w[59] >> 29)) & 1)
            | !(DV_II_51_0_BIT | DV_II_52_0_BIT);
    }
    if mask & (DV_II_51_0_BIT | DV_II_54_0_BIT) != 0 {
        mask &= (((w[58] >> 29) ^ (w[59] >> 29)) & 1).wrapping_sub(1)
            | !(DV_II_51_0_BIT | DV_II_54_0_BIT);
    }
    if mask & (DV_I_45_0_BIT | DV_II_45_0_BIT) != 0 {
        mask &= (0u32).wrapping_sub((w[60] ^ (w[61] >> 5)) & 1) | !(DV_I_45_0_BIT | DV_II_45_0_BIT);
    }
    if mask & (DV_I_46_0_BIT | DV_II_46_0_BIT) != 0 {
        mask &= (0u32).wrapping_sub((w[61] ^ (w[62] >> 5)) & 1) | !(DV_I_46_0_BIT | DV_II_46_0_BIT);
    }
    if mask & (DV_I_46_2_BIT | DV_II_46_2_BIT) != 0 {
        mask &= (0u32).wrapping_sub(((w[61] >> 2) ^ (w[62] >> 7)) & 1)
            | !(DV_I_46_2_BIT | DV_II_46_2_BIT);
    }
    if mask & (DV_I_47_0_BIT | DV_II_47_0_BIT) != 0 {
        mask &= (0u32).wrapping_sub((w[62] ^ (w[63] >> 5)) & 1) | !(DV_I_47_0_BIT | DV_II_47_0_BIT);
    }
    if mask & (DV_I_48_0_BIT | DV_II_48_0_BIT) != 0 {
        mask &= (0u32).wrapping_sub((w[63] ^ (w[64] >> 5)) & 1) | !(DV_I_48_0_BIT | DV_II_48_0_BIT);
    }
    if mask & (DV_I_45_0_BIT | DV_II_45_0_BIT) != 0 {
        mask &= (0u32).wrapping_sub(((w[63] >> 1) ^ (w[64] >> 6)) & 1)
            | !(DV_I_45_0_BIT | DV_II_45_0_BIT);
    }

    if mask == 0 {
        return 0;
    }

    if mask & (DV_I_43_0_BIT | DV_I_44_0_BIT | DV_I_46_2_BIT) != 0 {
        if mask & DV_I_43_0_BIT != 0
            && ((w[58] ^ (w[59] >> 5)) & 1 == 0
                || (w[58] ^ (w[63] >> 30)) & 1 == 0
                || ((w[61] >> 1) ^ (w[62] >> 6)) & 1 == 0)
        {
            mask &= !DV_I_43_0_BIT;
        }
        if mask & DV_I_44_0_BIT != 0
            && ((w[59] ^ (w[60] >> 5)) & 1 == 0
                || (w[59] ^ (w[64] >> 30)) & 1 == 0
                || ((w[62] >> 1) ^ (w[63] >> 6)) & 1 == 0)
        {
            mask &= !DV_I_44_0_BIT;
        }
        if mask & DV_I_46_2_BIT != 0 && ((w[39] >> 1) ^ (w[42] >> 6)) & 1 == 0 {
            mask &= !DV_I_46_2_BIT;
        }
    }

    if mask & (DV_I_47_2_BIT | DV_I_48_2_BIT | DV_I_49_2_BIT) != 0 {
        if mask & DV_I_47_2_BIT != 0 && ((w[62] >> 2) ^ (w[63] >> 7)) & 1 == 0 {
            mask &= !DV_I_47_2_BIT;
        }
        if mask & DV_I_48_2_BIT != 0
            && (((w[41] >> 1) ^ (w[49] >> 1)) & 1 == 0 || ((w[63] >> 2) ^ (w[64] >> 7)) & 1 == 0)
        {
            mask &= !DV_I_48_2_BIT;
        }
        if mask & DV_I_49_2_BIT != 0
            && (((w[38] >> 1) ^ (w[40] >> 1)) & 1 == 0 || ((w[42] >> 1) ^ (w[50] >> 1)) & 1 == 0)
        {
            mask &= !DV_I_49_2_BIT;
        }
    }

    if mask == 0 {
        return 0;
    }

    if mask & (DV_I_50_0_BIT | DV_I_50_2_BIT | DV_I_51_0_BIT) != 0 {
        if mask & DV_I_50_0_BIT != 0 && ((w[36] >> 4) ^ (w[37] >> 4)) & 1 == 0 {
            mask &= !DV_I_50_0_BIT;
        }
        if mask & DV_I_50_2_BIT != 0 && ((w[43] >> 1) ^ (w[44] >> 6)) & 1 == 0 {
            mask &= !DV_I_50_2_BIT;
        }
        if mask & DV_I_51_0_BIT != 0 && ((w[37] >> 4) ^ (w[38] >> 4)) & 1 == 0 {
            mask &= !DV_I_51_0_BIT;
        }
    }

    if mask & (DV_I_51_2_BIT | DV_I_52_0_BIT | DV_II_46_2_BIT) != 0 {
        if mask & DV_I_51_2_BIT != 0
            && (((w[35] >> 5) ^ (w[39] >> 30)) & 1 != 0
                || ((w[37] >> 1) ^ (w[37] >> 6)) & 1 != 0
                || ((w[44] >> 1) ^ (w[51] >> 6)) & 1 == 0
                || ((w[44] >> 1) ^ (w[52] >> 1)) & 1 == 0)
        {
            mask &= !DV_I_51_2_BIT;
        }
        if mask & DV_I_52_0_BIT != 0 && ((w[38] >> 4) ^ (w[39] >> 4)) & 1 == 0 {
            mask &= !DV_I_52_0_BIT;
        }
        if mask & DV_II_46_2_BIT != 0 && ((w[47] >> 1) ^ (w[48] >> 6)) & 1 == 0 {
            mask &= !DV_II_46_2_BIT;
        }
    }

    if mask == 0 {
        return 0;
    }

    if mask & (DV_II_48_0_BIT | DV_II_49_0_BIT | DV_II_49_2_BIT) != 0 {
        if mask & DV_II_48_0_BIT != 0
            && (((w[35] >> 30) ^ (w[36] >> 3)) & 1 == 0 || ((w[35] >> 30) ^ (w[40] >> 28)) & 1 == 0)
        {
            mask &= !DV_II_48_0_BIT;
        }
        if mask & DV_II_49_0_BIT != 0
            && (((w[36] >> 30) ^ (w[37] >> 3)) & 1 == 0 || ((w[36] >> 30) ^ (w[41] >> 28)) & 1 == 0)
        {
            mask &= !DV_II_49_0_BIT;
        }
        if mask & DV_II_49_2_BIT != 0
            && ((w[36] ^ (w[37] >> 5)) & 1 == 0
                || (w[36] ^ (w[41] >> 30)) & 1 == 0
                || ((w[44] >> 1) ^ (w[46] >> 1)) & 1 == 0
                || ((w[50] >> 1) ^ (w[51] >> 6)) & 1 == 0
                || ((w[50] >> 1) ^ (w[53] >> 6)) & 1 == 0
                || ((w[50] >> 1) ^ (w[54] >> 1)) & 1 == 0)
        {
            mask &= !DV_II_49_2_BIT;
        }
    }

    if mask & (DV_II_50_0_BIT | DV_II_50_2_BIT | DV_II_51_0_BIT) != 0 {
        if mask & DV_II_50_0_BIT != 0
            && (((w[37] >> 30) ^ (w[38] >> 3)) & 1 == 0 || ((w[37] >> 30) ^ (w[42] >> 28)) & 1 == 0)
        {
            mask &= !DV_II_50_0_BIT;
        }
        if mask & DV_II_50_2_BIT != 0
            && ((w[37] ^ (w[38] >> 5)) & 1 == 0
                || (w[37] ^ (w[42] >> 30)) & 1 == 0
                || ((w[45] >> 1) ^ (w[46] >> 6)) & 1 == 0
                || ((w[51] >> 1) ^ (w[52] >> 6)) & 1 == 0
                || ((w[51] >> 1) ^ (w[54] >> 6)) & 1 == 0
                || ((w[51] >> 1) ^ (w[55] >> 1)) & 1 == 0)
        {
            mask &= !DV_II_50_2_BIT;
        }
        if mask & DV_II_51_0_BIT != 0
            && (((w[38] >> 30) ^ (w[39] >> 3)) & 1 == 0 || ((w[38] >> 30) ^ (w[43] >> 28)) & 1 == 0)
        {
            mask &= !DV_II_51_0_BIT;
        }
    }

    if mask == 0 {
        return 0;
    }

    if mask & (DV_II_51_2_BIT | DV_II_52_0_BIT | DV_II_53_0_BIT) != 0 {
        if mask & DV_II_51_2_BIT != 0
            && ((w[38] ^ (w[39] >> 5)) & 1 == 0
                || (w[38] ^ (w[43] >> 30)) & 1 == 0
                || ((w[46] >> 1) ^ (w[47] >> 6)) & 1 == 0
                || ((w[52] >> 1) ^ (w[53] >> 6)) & 1 == 0
                || ((w[52] >> 1) ^ (w[55] >> 6)) & 1 == 0
                || ((w[52] >> 1) ^ (w[56] >> 1)) & 1 == 0)
        {
            mask &= !DV_II_51_2_BIT;
        }
        if mask & DV_II_52_0_BIT != 0
            && (((w[39] >> 30) ^ (w[40] >> 3)) & 1 == 0
                || ((w[39] >> 30) ^ (w[44] >> 28)) & 1 == 0
                || ((w[54] >> 4) ^ (w[60] >> 29)) & 1 == 0)
        {
            mask &= !DV_II_52_0_BIT;
        }
        if mask & DV_II_53_0_BIT != 0
            && (((w[41] >> 3) ^ (w[45] >> 28)) & 1 != 0
                || ((w[55] >> 4) ^ (w[57] >> 4)) & 1 == 0
                || ((w[55] >> 4) ^ (w[61] >> 29)) & 1 == 0)
        {
            mask &= !DV_II_53_0_BIT;
        }
    }

    if mask & (DV_II_54_0_BIT | DV_II_55_0_BIT | DV_II_56_0_BIT) != 0 {
        if mask & DV_II_54_0_BIT != 0
            && (((w[42] >> 3) ^ (w[46] >> 28)) & 1 != 0 || ((w[58] >> 4) ^ (w[62] >> 29)) & 1 != 0)
        {
            mask &= !DV_II_54_0_BIT;
        }
        if mask & DV_II_55_0_BIT != 0
            && (((w[43] >> 3) ^ (w[47] >> 28)) & 1 != 0
                || ((w[57] >> 4) ^ (w[59] >> 29)) & 1 != 0
                || ((w[59] >> 4) ^ (w[63] >> 29)) & 1 != 0)
        {
            mask &= !DV_II_55_0_BIT;
        }
        if mask & DV_II_56_0_BIT != 0
            && (((w[44] >> 3) ^ (w[48] >> 28)) & 1 != 0 || ((w[60] >> 4) ^ (w[64] >> 29)) & 1 != 0)
        {
            mask &= !DV_II_56_0_BIT;
        }
    }

    mask
}
