//! The unconditional UBC checks, AVX2 form.
//!
//! @generated by `codegen/` — do not edit by hand. Edit the table in
//! `codegen/src/ubc.rs` or the solver in `codegen/src/solve.rs` and
//! re-run it.

use crate::ubc_check::*;

/// # Safety
///
/// Requires `avx2`. Every load stays in `w`. The highest index read is 58.
#[target_feature(enable = "avx2")]
#[allow(unsafe_op_in_unsafe_fn)]
pub(crate) unsafe fn mask(w: &[u32; 80]) -> u32 {
    #[cfg(target_arch = "x86")]
    use core::arch::x86::*;
    #[cfg(target_arch = "x86_64")]
    use core::arch::x86_64::*;

    let p = w.as_ptr();
    let zero = _mm256_setzero_si256();
    let mut acc0 = zero;
    let mut acc1 = zero;

    {
        let near = _mm256_loadu_si256(p.add(35).cast());
        let far = _mm256_loadu_si256(p.add(36).cast());
        let x = _mm256_xor_si256(near, _mm256_srli_epi32(far, 5));
        let tested = _mm256_and_si256(x, _mm256_set1_epi32(1 << 1));
        let miss = _mm256_cmpeq_epi32(tested, zero);
        let bits = _mm256_setr_epi32(
            (DV_I_46_2_BIT | DV_I_49_2_BIT) as i32,
            (DV_I_47_2_BIT | DV_I_50_2_BIT | DV_II_46_2_BIT) as i32,
            (DV_I_48_2_BIT | DV_I_51_2_BIT) as i32,
            (DV_I_49_2_BIT) as i32,
            (DV_I_46_2_BIT | DV_I_50_2_BIT | DV_II_49_2_BIT) as i32,
            (DV_I_47_2_BIT | DV_I_51_2_BIT | DV_II_50_2_BIT) as i32,
            (DV_I_48_2_BIT | DV_II_46_2_BIT | DV_II_51_2_BIT) as i32,
            (DV_I_49_2_BIT) as i32,
        );
        acc0 = _mm256_or_si256(acc0, _mm256_and_si256(miss, bits));
    }

    {
        let near = _mm256_loadu_si256(p.add(35).cast());
        let far = _mm256_loadu_si256(p.add(39).cast());
        let x = _mm256_xor_si256(near, _mm256_srli_epi32(far, 25));
        let tested = _mm256_and_si256(x, _mm256_set1_epi32(1 << 4));
        let miss = _mm256_cmpeq_epi32(tested, zero);
        let bits = _mm256_setr_epi32(
            (DV_I_45_0_BIT | DV_I_48_0_BIT | DV_II_47_0_BIT) as i32,
            (DV_I_46_0_BIT | DV_I_49_0_BIT | DV_II_45_0_BIT | DV_II_48_0_BIT) as i32,
            (DV_I_47_0_BIT | DV_I_50_0_BIT | DV_II_46_0_BIT | DV_II_49_0_BIT) as i32,
            (DV_I_48_0_BIT | DV_I_51_0_BIT | DV_II_47_0_BIT | DV_II_50_0_BIT) as i32,
            (DV_I_49_0_BIT | DV_I_52_0_BIT | DV_II_48_0_BIT | DV_II_51_0_BIT) as i32,
            (DV_I_50_0_BIT | DV_II_49_0_BIT | DV_II_52_0_BIT) as i32,
            (DV_I_51_0_BIT | DV_II_45_0_BIT | DV_II_50_0_BIT | DV_II_53_0_BIT) as i32,
            (DV_I_52_0_BIT | DV_II_46_0_BIT | DV_II_51_0_BIT | DV_II_54_0_BIT) as i32,
        );
        acc1 = _mm256_or_si256(acc1, _mm256_andnot_si256(miss, bits));
    }

    {
        let near = _mm256_loadu_si256(p.add(39).cast());
        let far = _mm256_loadu_si256(p.add(40).cast());
        let x = _mm256_xor_si256(near, _mm256_srli_epi32(far, 25));
        let tested = _mm256_and_si256(x, _mm256_set1_epi32(1 << 4));
        let miss = _mm256_cmpeq_epi32(tested, zero);
        let bits = _mm256_setr_epi32(
            (DV_I_43_0_BIT | DV_II_53_0_BIT | DV_II_55_0_BIT) as i32,
            (DV_I_44_0_BIT | DV_II_54_0_BIT | DV_II_56_0_BIT) as i32,
            (DV_I_43_0_BIT | DV_I_45_0_BIT | DV_II_55_0_BIT) as i32,
            (DV_I_44_0_BIT | DV_I_46_0_BIT | DV_II_56_0_BIT) as i32,
            (DV_I_43_0_BIT | DV_I_45_0_BIT | DV_I_47_0_BIT) as i32,
            (DV_I_44_0_BIT | DV_I_46_0_BIT | DV_I_48_0_BIT) as i32,
            (DV_I_45_0_BIT | DV_I_47_0_BIT | DV_I_49_0_BIT) as i32,
            (DV_I_46_0_BIT | DV_I_48_0_BIT | DV_I_50_0_BIT) as i32,
        );
        acc0 = _mm256_or_si256(acc0, _mm256_and_si256(miss, bits));
    }

    {
        let near = _mm256_loadu_si256(p.add(37).cast());
        let far = _mm256_loadu_si256(p.add(40).cast());
        let x = _mm256_xor_si256(near, _mm256_srli_epi32(far, 25));
        let tested = _mm256_and_si256(x, _mm256_set1_epi32(1 << 4));
        let miss = _mm256_cmpeq_epi32(tested, zero);
        let bits = _mm256_setr_epi32(
            (DV_I_43_0_BIT | DV_I_47_0_BIT | DV_II_46_0_BIT | DV_II_53_0_BIT | DV_II_55_0_BIT)
                as i32,
            (DV_I_44_0_BIT | DV_I_48_0_BIT | DV_II_47_0_BIT | DV_II_54_0_BIT | DV_II_56_0_BIT)
                as i32,
            (DV_I_43_0_BIT | DV_I_45_0_BIT | DV_I_49_0_BIT | DV_II_48_0_BIT | DV_II_55_0_BIT)
                as i32,
            0,
            0,
            0,
            0,
            0,
        );
        acc1 = _mm256_or_si256(acc1, _mm256_andnot_si256(miss, bits));
    }

    {
        let near = _mm256_loadu_si256(p.add(42).cast());
        let far = _mm256_loadu_si256(p.add(43).cast());
        let x = _mm256_xor_si256(near, far);
        let tested = _mm256_and_si256(x, _mm256_set1_epi32(1 << 29));
        let miss = _mm256_cmpeq_epi32(tested, zero);
        let bits = _mm256_setr_epi32(
            (DV_I_46_0_BIT | DV_I_49_0_BIT | DV_I_50_0_BIT | DV_II_48_0_BIT | DV_II_49_0_BIT)
                as i32,
            (DV_I_47_0_BIT
                | DV_I_50_0_BIT
                | DV_I_51_0_BIT
                | DV_II_45_0_BIT
                | DV_II_49_0_BIT
                | DV_II_50_0_BIT) as i32,
            (DV_I_48_0_BIT
                | DV_I_51_0_BIT
                | DV_I_52_0_BIT
                | DV_II_45_0_BIT
                | DV_II_46_0_BIT
                | DV_II_50_0_BIT
                | DV_II_51_0_BIT) as i32,
            (DV_I_49_0_BIT
                | DV_I_52_0_BIT
                | DV_II_46_0_BIT
                | DV_II_47_0_BIT
                | DV_II_51_0_BIT
                | DV_II_52_0_BIT) as i32,
            (DV_I_43_0_BIT
                | DV_I_50_0_BIT
                | DV_II_47_0_BIT
                | DV_II_48_0_BIT
                | DV_II_52_0_BIT
                | DV_II_53_0_BIT) as i32,
            (DV_I_44_0_BIT
                | DV_I_51_0_BIT
                | DV_II_48_0_BIT
                | DV_II_49_0_BIT
                | DV_II_53_0_BIT
                | DV_II_54_0_BIT) as i32,
            (DV_I_45_0_BIT
                | DV_I_52_0_BIT
                | DV_II_49_0_BIT
                | DV_II_50_0_BIT
                | DV_II_54_0_BIT
                | DV_II_55_0_BIT) as i32,
            (DV_I_46_0_BIT
                | DV_II_45_0_BIT
                | DV_II_50_0_BIT
                | DV_II_51_0_BIT
                | DV_II_55_0_BIT
                | DV_II_56_0_BIT) as i32,
        );
        acc0 = _mm256_or_si256(acc0, _mm256_andnot_si256(miss, bits));
    }

    {
        let near = _mm256_loadu_si256(p.add(40).cast());
        let far = _mm256_loadu_si256(p.add(43).cast());
        let x = _mm256_xor_si256(near, _mm256_srli_epi32(far, 25));
        let tested = _mm256_and_si256(x, _mm256_set1_epi32(1 << 4));
        let miss = _mm256_cmpeq_epi32(tested, zero);
        let bits = _mm256_setr_epi32(
            (DV_I_44_0_BIT | DV_I_46_0_BIT | DV_I_50_0_BIT | DV_II_49_0_BIT | DV_II_56_0_BIT)
                as i32,
            (DV_I_43_0_BIT
                | DV_I_45_0_BIT
                | DV_I_47_0_BIT
                | DV_I_51_0_BIT
                | DV_II_45_0_BIT
                | DV_II_50_0_BIT) as i32,
            (DV_I_44_0_BIT
                | DV_I_46_0_BIT
                | DV_I_48_0_BIT
                | DV_I_52_0_BIT
                | DV_II_46_0_BIT
                | DV_II_51_0_BIT) as i32,
            (DV_I_43_0_BIT
                | DV_I_45_0_BIT
                | DV_I_47_0_BIT
                | DV_I_49_0_BIT
                | DV_II_47_0_BIT
                | DV_II_52_0_BIT) as i32,
            (DV_I_44_0_BIT
                | DV_I_46_0_BIT
                | DV_I_48_0_BIT
                | DV_I_50_0_BIT
                | DV_II_48_0_BIT
                | DV_II_53_0_BIT) as i32,
            (DV_I_45_0_BIT
                | DV_I_47_0_BIT
                | DV_I_49_0_BIT
                | DV_I_51_0_BIT
                | DV_II_49_0_BIT
                | DV_II_54_0_BIT) as i32,
            (DV_I_46_0_BIT
                | DV_I_48_0_BIT
                | DV_I_50_0_BIT
                | DV_I_52_0_BIT
                | DV_II_50_0_BIT
                | DV_II_55_0_BIT) as i32,
            (DV_I_47_0_BIT
                | DV_I_49_0_BIT
                | DV_I_51_0_BIT
                | DV_II_45_0_BIT
                | DV_II_51_0_BIT
                | DV_II_56_0_BIT) as i32,
        );
        acc1 = _mm256_or_si256(acc1, _mm256_andnot_si256(miss, bits));
    }

    {
        let near = _mm256_loadu_si256(p.add(41).cast());
        let far = _mm256_loadu_si256(p.add(43).cast());
        let x = _mm256_xor_si256(near, far);
        let tested = _mm256_and_si256(x, _mm256_set1_epi32(1 << 6));
        let miss = _mm256_cmpeq_epi32(tested, zero);
        let bits = _mm256_setr_epi32(
            (DV_I_47_2_BIT) as i32,
            (DV_I_46_2_BIT | DV_I_48_2_BIT) as i32,
            (DV_I_47_2_BIT | DV_I_49_2_BIT) as i32,
            (DV_I_46_2_BIT | DV_I_48_2_BIT | DV_I_50_2_BIT) as i32,
            (DV_I_47_2_BIT | DV_I_49_2_BIT | DV_I_51_2_BIT) as i32,
            (DV_I_48_2_BIT | DV_I_50_2_BIT) as i32,
            (DV_I_49_2_BIT | DV_I_51_2_BIT) as i32,
            (DV_I_50_2_BIT | DV_II_46_2_BIT) as i32,
        );
        acc0 = _mm256_or_si256(acc0, _mm256_andnot_si256(miss, bits));
    }

    {
        let near = _mm256_loadu_si256(p.add(47).cast());
        let far = _mm256_loadu_si256(p.add(48).cast());
        let x = _mm256_xor_si256(near, _mm256_srli_epi32(far, 25));
        let tested = _mm256_and_si256(x, _mm256_set1_epi32(1 << 4));
        let miss = _mm256_cmpeq_epi32(tested, zero);
        let bits = _mm256_setr_epi32(
            (DV_I_47_0_BIT | DV_I_49_0_BIT | DV_I_51_0_BIT) as i32,
            (DV_I_48_0_BIT | DV_I_50_0_BIT | DV_I_52_0_BIT) as i32,
            (DV_I_49_0_BIT | DV_I_51_0_BIT | DV_II_45_0_BIT) as i32,
            (DV_I_50_0_BIT | DV_I_52_0_BIT | DV_II_46_0_BIT) as i32,
            (DV_I_51_0_BIT | DV_II_47_0_BIT) as i32,
            (DV_I_52_0_BIT | DV_II_48_0_BIT) as i32,
            (DV_II_49_0_BIT) as i32,
            (DV_II_50_0_BIT) as i32,
        );
        acc1 = _mm256_or_si256(acc1, _mm256_and_si256(miss, bits));
    }

    {
        let near = _mm256_loadu_si256(p.add(50).cast());
        let far = _mm256_loadu_si256(p.add(51).cast());
        let x = _mm256_xor_si256(near, far);
        let tested = _mm256_and_si256(x, _mm256_set1_epi32(1 << 29));
        let miss = _mm256_cmpeq_epi32(tested, zero);
        let bits = _mm256_setr_epi32(
            (DV_I_47_0_BIT | DV_II_46_0_BIT | DV_II_51_0_BIT | DV_II_52_0_BIT | DV_II_56_0_BIT)
                as i32,
            (DV_I_48_0_BIT | DV_II_47_0_BIT | DV_II_52_0_BIT | DV_II_53_0_BIT) as i32,
            (DV_I_49_0_BIT | DV_II_45_0_BIT | DV_II_48_0_BIT | DV_II_53_0_BIT | DV_II_54_0_BIT)
                as i32,
            (DV_I_50_0_BIT | DV_II_46_0_BIT | DV_II_49_0_BIT | DV_II_54_0_BIT | DV_II_55_0_BIT)
                as i32,
            (DV_I_51_0_BIT | DV_II_47_0_BIT | DV_II_50_0_BIT | DV_II_55_0_BIT | DV_II_56_0_BIT)
                as i32,
            (DV_I_52_0_BIT | DV_II_48_0_BIT | DV_II_51_0_BIT | DV_II_56_0_BIT) as i32,
            (DV_II_49_0_BIT | DV_II_52_0_BIT) as i32,
            (DV_II_50_0_BIT | DV_II_53_0_BIT) as i32,
        );
        acc0 = _mm256_or_si256(acc0, _mm256_andnot_si256(miss, bits));
    }

    {
        let near = _mm256_loadu_si256(p.add(48).cast());
        let far = _mm256_loadu_si256(p.add(51).cast());
        let x = _mm256_xor_si256(near, _mm256_srli_epi32(far, 25));
        let tested = _mm256_and_si256(x, _mm256_set1_epi32(1 << 4));
        let miss = _mm256_cmpeq_epi32(tested, zero);
        let bits = _mm256_setr_epi32(
            (DV_I_48_0_BIT | DV_I_50_0_BIT | DV_I_52_0_BIT | DV_II_46_0_BIT | DV_II_52_0_BIT)
                as i32,
            (DV_I_49_0_BIT | DV_I_51_0_BIT | DV_II_45_0_BIT | DV_II_47_0_BIT | DV_II_53_0_BIT)
                as i32,
            (DV_I_50_0_BIT | DV_I_52_0_BIT | DV_II_46_0_BIT | DV_II_48_0_BIT | DV_II_54_0_BIT)
                as i32,
            (DV_I_51_0_BIT | DV_II_47_0_BIT | DV_II_49_0_BIT | DV_II_55_0_BIT) as i32,
            (DV_I_52_0_BIT | DV_II_48_0_BIT | DV_II_50_0_BIT | DV_II_56_0_BIT) as i32,
            (DV_II_49_0_BIT | DV_II_51_0_BIT) as i32,
            (DV_II_50_0_BIT | DV_II_52_0_BIT) as i32,
            (DV_II_51_0_BIT | DV_II_53_0_BIT) as i32,
        );
        acc1 = _mm256_or_si256(acc1, _mm256_andnot_si256(miss, bits));
    }

    let acc = _mm256_or_si256(acc0, acc1);
    let acc = _mm_or_si128(
        _mm256_castsi256_si128(acc),
        _mm256_extracti128_si256::<1>(acc),
    );
    let acc = _mm_or_si128(acc, _mm_shuffle_epi32(acc, 0b01_00_11_10));
    let acc = _mm_or_si128(acc, _mm_shuffle_epi32(acc, 0b10_11_00_01));
    !(_mm_cvtsi128_si32(acc) as u32)
}
