//! The unconditional UBC checks, `aarch64` NEON form.
//!
//! @generated by `codegen/` — do not edit by hand. Edit the table in
//! `codegen/src/ubc.rs` or the solver in `codegen/src/solve.rs` and
//! re-run it.

use crate::ubc_check::*;

/// # Safety
///
/// Requires `neon`. Every load stays in `w`. The highest index read is 58.
#[target_feature(enable = "neon")]
#[allow(unsafe_op_in_unsafe_fn)]
pub(crate) unsafe fn mask(w: &[u32; 80]) -> u32 {
    use core::arch::aarch64::*;

    let p = w.as_ptr();
    let mut acc0 = vdupq_n_u32(0);
    let mut acc1 = vdupq_n_u32(0);

    {
        let near = vld1q_u32(p.add(35));
        let far = vld1q_u32(p.add(36));
        let x = veorq_u32(near, vshrq_n_u32(far, 5));
        let hit = vceqq_u32(vandq_u32(x, vdupq_n_u32(1 << 1)), vdupq_n_u32(0));
        let bits = vld1q_u32(
            [
                DV_I_46_2_BIT | DV_I_49_2_BIT,
                DV_I_47_2_BIT | DV_I_50_2_BIT | DV_II_46_2_BIT,
                DV_I_48_2_BIT | DV_I_51_2_BIT,
                DV_I_49_2_BIT,
            ]
            .as_ptr(),
        );
        acc0 = vorrq_u32(acc0, vandq_u32(hit, bits));
    }

    {
        let near = vld1q_u32(p.add(35));
        let far = vld1q_u32(p.add(39));
        let x = veorq_u32(near, vshrq_n_u32(far, 25));
        let hit = vtstq_u32(x, vdupq_n_u32(1 << 4));
        let bits = vld1q_u32(
            [
                DV_I_45_0_BIT | DV_I_48_0_BIT | DV_II_47_0_BIT,
                DV_I_46_0_BIT | DV_I_49_0_BIT | DV_II_45_0_BIT | DV_II_48_0_BIT,
                DV_I_47_0_BIT | DV_I_50_0_BIT | DV_II_46_0_BIT | DV_II_49_0_BIT,
                DV_I_48_0_BIT | DV_I_51_0_BIT | DV_II_47_0_BIT | DV_II_50_0_BIT,
            ]
            .as_ptr(),
        );
        acc1 = vorrq_u32(acc1, vandq_u32(hit, bits));
    }

    {
        let near = vld1q_u32(p.add(39));
        let far = vld1q_u32(p.add(40));
        let x = veorq_u32(near, vshrq_n_u32(far, 25));
        let hit = vceqq_u32(vandq_u32(x, vdupq_n_u32(1 << 4)), vdupq_n_u32(0));
        let bits = vld1q_u32(
            [
                DV_I_43_0_BIT | DV_II_53_0_BIT | DV_II_55_0_BIT,
                DV_I_44_0_BIT | DV_II_54_0_BIT | DV_II_56_0_BIT,
                DV_I_43_0_BIT | DV_I_45_0_BIT | DV_II_55_0_BIT,
                DV_I_44_0_BIT | DV_I_46_0_BIT | DV_II_56_0_BIT,
            ]
            .as_ptr(),
        );
        acc0 = vorrq_u32(acc0, vandq_u32(hit, bits));
    }

    {
        let near = vld1q_u32(p.add(39));
        let far = vld1q_u32(p.add(40));
        let x = veorq_u32(near, vshrq_n_u32(far, 5));
        let hit = vceqq_u32(vandq_u32(x, vdupq_n_u32(1 << 1)), vdupq_n_u32(0));
        let bits = vld1q_u32(
            [
                DV_I_46_2_BIT | DV_I_50_2_BIT | DV_II_49_2_BIT,
                DV_I_47_2_BIT | DV_I_51_2_BIT | DV_II_50_2_BIT,
                DV_I_48_2_BIT | DV_II_46_2_BIT | DV_II_51_2_BIT,
                DV_I_49_2_BIT,
            ]
            .as_ptr(),
        );
        acc1 = vorrq_u32(acc1, vandq_u32(hit, bits));
    }

    {
        let near = vld1q_u32(p.add(37));
        let far = vld1q_u32(p.add(40));
        let x = veorq_u32(near, vshrq_n_u32(far, 25));
        let hit = vtstq_u32(x, vdupq_n_u32(1 << 4));
        let bits = vld1q_u32(
            [
                DV_I_43_0_BIT | DV_I_47_0_BIT | DV_II_46_0_BIT | DV_II_53_0_BIT | DV_II_55_0_BIT,
                DV_I_44_0_BIT | DV_I_48_0_BIT | DV_II_47_0_BIT | DV_II_54_0_BIT | DV_II_56_0_BIT,
                DV_I_43_0_BIT | DV_I_45_0_BIT | DV_I_49_0_BIT | DV_II_48_0_BIT | DV_II_55_0_BIT,
                0,
            ]
            .as_ptr(),
        );
        acc0 = vorrq_u32(acc0, vandq_u32(hit, bits));
    }

    {
        let near = vld1q_u32(p.add(42));
        let far = vld1q_u32(p.add(43));
        let x = veorq_u32(near, far);
        let hit = vtstq_u32(x, vdupq_n_u32(1 << 29));
        let bits = vld1q_u32(
            [
                DV_I_46_0_BIT | DV_I_49_0_BIT | DV_I_50_0_BIT | DV_II_48_0_BIT | DV_II_49_0_BIT,
                DV_I_47_0_BIT
                    | DV_I_50_0_BIT
                    | DV_I_51_0_BIT
                    | DV_II_45_0_BIT
                    | DV_II_49_0_BIT
                    | DV_II_50_0_BIT,
                DV_I_48_0_BIT
                    | DV_I_51_0_BIT
                    | DV_I_52_0_BIT
                    | DV_II_45_0_BIT
                    | DV_II_46_0_BIT
                    | DV_II_50_0_BIT
                    | DV_II_51_0_BIT,
                DV_I_49_0_BIT
                    | DV_I_52_0_BIT
                    | DV_II_46_0_BIT
                    | DV_II_47_0_BIT
                    | DV_II_51_0_BIT
                    | DV_II_52_0_BIT,
            ]
            .as_ptr(),
        );
        acc1 = vorrq_u32(acc1, vandq_u32(hit, bits));
    }

    {
        let near = vld1q_u32(p.add(40));
        let far = vld1q_u32(p.add(43));
        let x = veorq_u32(near, vshrq_n_u32(far, 25));
        let hit = vtstq_u32(x, vdupq_n_u32(1 << 4));
        let bits = vld1q_u32(
            [
                DV_I_44_0_BIT | DV_I_46_0_BIT | DV_I_50_0_BIT | DV_II_49_0_BIT | DV_II_56_0_BIT,
                DV_I_43_0_BIT
                    | DV_I_45_0_BIT
                    | DV_I_47_0_BIT
                    | DV_I_51_0_BIT
                    | DV_II_45_0_BIT
                    | DV_II_50_0_BIT,
                DV_I_44_0_BIT
                    | DV_I_46_0_BIT
                    | DV_I_48_0_BIT
                    | DV_I_52_0_BIT
                    | DV_II_46_0_BIT
                    | DV_II_51_0_BIT,
                DV_I_43_0_BIT
                    | DV_I_45_0_BIT
                    | DV_I_47_0_BIT
                    | DV_I_49_0_BIT
                    | DV_II_47_0_BIT
                    | DV_II_52_0_BIT,
            ]
            .as_ptr(),
        );
        acc0 = vorrq_u32(acc0, vandq_u32(hit, bits));
    }

    {
        let near = vld1q_u32(p.add(39));
        let far = vld1q_u32(p.add(43));
        let x = veorq_u32(near, vshrq_n_u32(far, 25));
        let hit = vtstq_u32(x, vdupq_n_u32(1 << 4));
        let bits = vld1q_u32(
            [
                DV_I_49_0_BIT | DV_I_52_0_BIT | DV_II_48_0_BIT | DV_II_51_0_BIT,
                DV_I_50_0_BIT | DV_II_49_0_BIT | DV_II_52_0_BIT,
                DV_I_51_0_BIT | DV_II_45_0_BIT | DV_II_50_0_BIT | DV_II_53_0_BIT,
                DV_I_52_0_BIT | DV_II_46_0_BIT | DV_II_51_0_BIT | DV_II_54_0_BIT,
            ]
            .as_ptr(),
        );
        acc1 = vorrq_u32(acc1, vandq_u32(hit, bits));
    }

    {
        let near = vld1q_u32(p.add(41));
        let far = vld1q_u32(p.add(43));
        let x = veorq_u32(near, far);
        let hit = vtstq_u32(x, vdupq_n_u32(1 << 6));
        let bits = vld1q_u32(
            [
                DV_I_47_2_BIT,
                DV_I_46_2_BIT | DV_I_48_2_BIT,
                DV_I_47_2_BIT | DV_I_49_2_BIT,
                DV_I_46_2_BIT | DV_I_48_2_BIT | DV_I_50_2_BIT,
            ]
            .as_ptr(),
        );
        acc0 = vorrq_u32(acc0, vandq_u32(hit, bits));
    }

    {
        let near = vld1q_u32(p.add(43));
        let far = vld1q_u32(p.add(44));
        let x = veorq_u32(near, vshrq_n_u32(far, 25));
        let hit = vceqq_u32(vandq_u32(x, vdupq_n_u32(1 << 4)), vdupq_n_u32(0));
        let bits = vld1q_u32(
            [
                DV_I_43_0_BIT | DV_I_45_0_BIT | DV_I_47_0_BIT,
                DV_I_44_0_BIT | DV_I_46_0_BIT | DV_I_48_0_BIT,
                DV_I_45_0_BIT | DV_I_47_0_BIT | DV_I_49_0_BIT,
                DV_I_46_0_BIT | DV_I_48_0_BIT | DV_I_50_0_BIT,
            ]
            .as_ptr(),
        );
        acc1 = vorrq_u32(acc1, vandq_u32(hit, bits));
    }

    {
        let near = vld1q_u32(p.add(46));
        let far = vld1q_u32(p.add(47));
        let x = veorq_u32(near, far);
        let hit = vtstq_u32(x, vdupq_n_u32(1 << 29));
        let bits = vld1q_u32(
            [
                DV_I_43_0_BIT
                    | DV_I_50_0_BIT
                    | DV_II_47_0_BIT
                    | DV_II_48_0_BIT
                    | DV_II_52_0_BIT
                    | DV_II_53_0_BIT,
                DV_I_44_0_BIT
                    | DV_I_51_0_BIT
                    | DV_II_48_0_BIT
                    | DV_II_49_0_BIT
                    | DV_II_53_0_BIT
                    | DV_II_54_0_BIT,
                DV_I_45_0_BIT
                    | DV_I_52_0_BIT
                    | DV_II_49_0_BIT
                    | DV_II_50_0_BIT
                    | DV_II_54_0_BIT
                    | DV_II_55_0_BIT,
                DV_I_46_0_BIT
                    | DV_II_45_0_BIT
                    | DV_II_50_0_BIT
                    | DV_II_51_0_BIT
                    | DV_II_55_0_BIT
                    | DV_II_56_0_BIT,
            ]
            .as_ptr(),
        );
        acc0 = vorrq_u32(acc0, vandq_u32(hit, bits));
    }

    {
        let near = vld1q_u32(p.add(44));
        let far = vld1q_u32(p.add(47));
        let x = veorq_u32(near, vshrq_n_u32(far, 25));
        let hit = vtstq_u32(x, vdupq_n_u32(1 << 4));
        let bits = vld1q_u32(
            [
                DV_I_44_0_BIT
                    | DV_I_46_0_BIT
                    | DV_I_48_0_BIT
                    | DV_I_50_0_BIT
                    | DV_II_48_0_BIT
                    | DV_II_53_0_BIT,
                DV_I_45_0_BIT
                    | DV_I_47_0_BIT
                    | DV_I_49_0_BIT
                    | DV_I_51_0_BIT
                    | DV_II_49_0_BIT
                    | DV_II_54_0_BIT,
                DV_I_46_0_BIT
                    | DV_I_48_0_BIT
                    | DV_I_50_0_BIT
                    | DV_I_52_0_BIT
                    | DV_II_50_0_BIT
                    | DV_II_55_0_BIT,
                DV_I_47_0_BIT
                    | DV_I_49_0_BIT
                    | DV_I_51_0_BIT
                    | DV_II_45_0_BIT
                    | DV_II_51_0_BIT
                    | DV_II_56_0_BIT,
            ]
            .as_ptr(),
        );
        acc1 = vorrq_u32(acc1, vandq_u32(hit, bits));
    }

    {
        let near = vld1q_u32(p.add(45));
        let far = vld1q_u32(p.add(47));
        let x = veorq_u32(near, far);
        let hit = vtstq_u32(x, vdupq_n_u32(1 << 6));
        let bits = vld1q_u32(
            [
                DV_I_47_2_BIT | DV_I_49_2_BIT | DV_I_51_2_BIT,
                DV_I_48_2_BIT | DV_I_50_2_BIT,
                DV_I_49_2_BIT | DV_I_51_2_BIT,
                DV_I_50_2_BIT | DV_II_46_2_BIT,
            ]
            .as_ptr(),
        );
        acc0 = vorrq_u32(acc0, vandq_u32(hit, bits));
    }

    {
        let near = vld1q_u32(p.add(47));
        let far = vld1q_u32(p.add(48));
        let x = veorq_u32(near, vshrq_n_u32(far, 25));
        let hit = vceqq_u32(vandq_u32(x, vdupq_n_u32(1 << 4)), vdupq_n_u32(0));
        let bits = vld1q_u32(
            [
                DV_I_47_0_BIT | DV_I_49_0_BIT | DV_I_51_0_BIT,
                DV_I_48_0_BIT | DV_I_50_0_BIT | DV_I_52_0_BIT,
                DV_I_49_0_BIT | DV_I_51_0_BIT | DV_II_45_0_BIT,
                DV_I_50_0_BIT | DV_I_52_0_BIT | DV_II_46_0_BIT,
            ]
            .as_ptr(),
        );
        acc1 = vorrq_u32(acc1, vandq_u32(hit, bits));
    }

    {
        let near = vld1q_u32(p.add(50));
        let far = vld1q_u32(p.add(51));
        let x = veorq_u32(near, far);
        let hit = vtstq_u32(x, vdupq_n_u32(1 << 29));
        let bits = vld1q_u32(
            [
                DV_I_47_0_BIT | DV_II_46_0_BIT | DV_II_51_0_BIT | DV_II_52_0_BIT | DV_II_56_0_BIT,
                DV_I_48_0_BIT | DV_II_47_0_BIT | DV_II_52_0_BIT | DV_II_53_0_BIT,
                DV_I_49_0_BIT | DV_II_45_0_BIT | DV_II_48_0_BIT | DV_II_53_0_BIT | DV_II_54_0_BIT,
                DV_I_50_0_BIT | DV_II_46_0_BIT | DV_II_49_0_BIT | DV_II_54_0_BIT | DV_II_55_0_BIT,
            ]
            .as_ptr(),
        );
        acc0 = vorrq_u32(acc0, vandq_u32(hit, bits));
    }

    {
        let near = vld1q_u32(p.add(48));
        let far = vld1q_u32(p.add(51));
        let x = veorq_u32(near, vshrq_n_u32(far, 25));
        let hit = vtstq_u32(x, vdupq_n_u32(1 << 4));
        let bits = vld1q_u32(
            [
                DV_I_48_0_BIT | DV_I_50_0_BIT | DV_I_52_0_BIT | DV_II_46_0_BIT | DV_II_52_0_BIT,
                DV_I_49_0_BIT | DV_I_51_0_BIT | DV_II_45_0_BIT | DV_II_47_0_BIT | DV_II_53_0_BIT,
                DV_I_50_0_BIT | DV_I_52_0_BIT | DV_II_46_0_BIT | DV_II_48_0_BIT | DV_II_54_0_BIT,
                DV_I_51_0_BIT | DV_II_47_0_BIT | DV_II_49_0_BIT | DV_II_55_0_BIT,
            ]
            .as_ptr(),
        );
        acc1 = vorrq_u32(acc1, vandq_u32(hit, bits));
    }

    {
        let near = vld1q_u32(p.add(51));
        let far = vld1q_u32(p.add(52));
        let x = veorq_u32(near, vshrq_n_u32(far, 25));
        let hit = vceqq_u32(vandq_u32(x, vdupq_n_u32(1 << 4)), vdupq_n_u32(0));
        let bits = vld1q_u32(
            [
                DV_I_51_0_BIT | DV_II_47_0_BIT,
                DV_I_52_0_BIT | DV_II_48_0_BIT,
                DV_II_49_0_BIT,
                DV_II_50_0_BIT,
            ]
            .as_ptr(),
        );
        acc0 = vorrq_u32(acc0, vandq_u32(hit, bits));
    }

    {
        let near = vld1q_u32(p.add(54));
        let far = vld1q_u32(p.add(55));
        let x = veorq_u32(near, far);
        let hit = vtstq_u32(x, vdupq_n_u32(1 << 29));
        let bits = vld1q_u32(
            [
                DV_I_51_0_BIT | DV_II_47_0_BIT | DV_II_50_0_BIT | DV_II_55_0_BIT | DV_II_56_0_BIT,
                DV_I_52_0_BIT | DV_II_48_0_BIT | DV_II_51_0_BIT | DV_II_56_0_BIT,
                DV_II_49_0_BIT | DV_II_52_0_BIT,
                DV_II_50_0_BIT | DV_II_53_0_BIT,
            ]
            .as_ptr(),
        );
        acc1 = vorrq_u32(acc1, vandq_u32(hit, bits));
    }

    {
        let near = vld1q_u32(p.add(52));
        let far = vld1q_u32(p.add(55));
        let x = veorq_u32(near, vshrq_n_u32(far, 25));
        let hit = vtstq_u32(x, vdupq_n_u32(1 << 4));
        let bits = vld1q_u32(
            [
                DV_I_52_0_BIT | DV_II_48_0_BIT | DV_II_50_0_BIT | DV_II_56_0_BIT,
                DV_II_49_0_BIT | DV_II_51_0_BIT,
                DV_II_50_0_BIT | DV_II_52_0_BIT,
                DV_II_51_0_BIT | DV_II_53_0_BIT,
            ]
            .as_ptr(),
        );
        acc0 = vorrq_u32(acc0, vandq_u32(hit, bits));
    }

    let acc = vorrq_u32(acc0, acc1);
    let folded = vorr_u32(vget_low_u32(acc), vget_high_u32(acc));
    let cleared = vget_lane_u32(vorr_u32(folded, vdup_lane_u32(folded, 1)), 0);
    !cleared
}
