//! The unconditional UBC checks, scalar reference form.
//!
//! @generated by `codegen/` — do not edit by hand. Edit the table in
//! `codegen/src/ubc.rs` or the solver in `codegen/src/solve.rs` and
//! re-run it.

use crate::ubc_check::*;

#[allow(dead_code)]
#[inline(always)]
pub(crate) fn mask(w: &[u32; 80]) -> u32 {
    let mut mask: u32 = !0;

    mask &= (((w[42] >> 29) ^ (w[43] >> 29)) & 1).wrapping_sub(1)
        | !(DV_I_46_0_BIT | DV_I_49_0_BIT | DV_I_50_0_BIT | DV_II_48_0_BIT | DV_II_49_0_BIT);
    mask &= (((w[43] >> 29) ^ (w[44] >> 29)) & 1).wrapping_sub(1)
        | !(DV_I_47_0_BIT
            | DV_I_50_0_BIT
            | DV_I_51_0_BIT
            | DV_II_45_0_BIT
            | DV_II_49_0_BIT
            | DV_II_50_0_BIT);
    mask &= (((w[44] >> 29) ^ (w[45] >> 29)) & 1).wrapping_sub(1)
        | !(DV_I_48_0_BIT
            | DV_I_51_0_BIT
            | DV_I_52_0_BIT
            | DV_II_45_0_BIT
            | DV_II_46_0_BIT
            | DV_II_50_0_BIT
            | DV_II_51_0_BIT);
    mask &= (((w[45] >> 29) ^ (w[46] >> 29)) & 1).wrapping_sub(1)
        | !(DV_I_49_0_BIT
            | DV_I_52_0_BIT
            | DV_II_46_0_BIT
            | DV_II_47_0_BIT
            | DV_II_51_0_BIT
            | DV_II_52_0_BIT);
    mask &= (((w[46] >> 29) ^ (w[47] >> 29)) & 1).wrapping_sub(1)
        | !(DV_I_43_0_BIT
            | DV_I_50_0_BIT
            | DV_II_47_0_BIT
            | DV_II_48_0_BIT
            | DV_II_52_0_BIT
            | DV_II_53_0_BIT);
    mask &= (((w[47] >> 29) ^ (w[48] >> 29)) & 1).wrapping_sub(1)
        | !(DV_I_44_0_BIT
            | DV_I_51_0_BIT
            | DV_II_48_0_BIT
            | DV_II_49_0_BIT
            | DV_II_53_0_BIT
            | DV_II_54_0_BIT);
    mask &= (((w[48] >> 29) ^ (w[49] >> 29)) & 1).wrapping_sub(1)
        | !(DV_I_45_0_BIT
            | DV_I_52_0_BIT
            | DV_II_49_0_BIT
            | DV_II_50_0_BIT
            | DV_II_54_0_BIT
            | DV_II_55_0_BIT);
    mask &= (((w[49] >> 29) ^ (w[50] >> 29)) & 1).wrapping_sub(1)
        | !(DV_I_46_0_BIT
            | DV_II_45_0_BIT
            | DV_II_50_0_BIT
            | DV_II_51_0_BIT
            | DV_II_55_0_BIT
            | DV_II_56_0_BIT);

    mask &= (((w[40] >> 4) ^ (w[43] >> 29)) & 1).wrapping_sub(1)
        | !(DV_I_44_0_BIT | DV_I_46_0_BIT | DV_I_50_0_BIT | DV_II_49_0_BIT | DV_II_56_0_BIT);
    mask &= (((w[41] >> 4) ^ (w[44] >> 29)) & 1).wrapping_sub(1)
        | !(DV_I_43_0_BIT
            | DV_I_45_0_BIT
            | DV_I_47_0_BIT
            | DV_I_51_0_BIT
            | DV_II_45_0_BIT
            | DV_II_50_0_BIT);
    mask &= (((w[42] >> 4) ^ (w[45] >> 29)) & 1).wrapping_sub(1)
        | !(DV_I_44_0_BIT
            | DV_I_46_0_BIT
            | DV_I_48_0_BIT
            | DV_I_52_0_BIT
            | DV_II_46_0_BIT
            | DV_II_51_0_BIT);
    mask &= (((w[43] >> 4) ^ (w[46] >> 29)) & 1).wrapping_sub(1)
        | !(DV_I_43_0_BIT
            | DV_I_45_0_BIT
            | DV_I_47_0_BIT
            | DV_I_49_0_BIT
            | DV_II_47_0_BIT
            | DV_II_52_0_BIT);
    mask &= (((w[44] >> 4) ^ (w[47] >> 29)) & 1).wrapping_sub(1)
        | !(DV_I_44_0_BIT
            | DV_I_46_0_BIT
            | DV_I_48_0_BIT
            | DV_I_50_0_BIT
            | DV_II_48_0_BIT
            | DV_II_53_0_BIT);
    mask &= (((w[45] >> 4) ^ (w[48] >> 29)) & 1).wrapping_sub(1)
        | !(DV_I_45_0_BIT
            | DV_I_47_0_BIT
            | DV_I_49_0_BIT
            | DV_I_51_0_BIT
            | DV_II_49_0_BIT
            | DV_II_54_0_BIT);
    mask &= (((w[46] >> 4) ^ (w[49] >> 29)) & 1).wrapping_sub(1)
        | !(DV_I_46_0_BIT
            | DV_I_48_0_BIT
            | DV_I_50_0_BIT
            | DV_I_52_0_BIT
            | DV_II_50_0_BIT
            | DV_II_55_0_BIT);
    mask &= (((w[47] >> 4) ^ (w[50] >> 29)) & 1).wrapping_sub(1)
        | !(DV_I_47_0_BIT
            | DV_I_49_0_BIT
            | DV_I_51_0_BIT
            | DV_II_45_0_BIT
            | DV_II_51_0_BIT
            | DV_II_56_0_BIT);

    mask &= (((w[50] >> 29) ^ (w[51] >> 29)) & 1).wrapping_sub(1)
        | !(DV_I_47_0_BIT | DV_II_46_0_BIT | DV_II_51_0_BIT | DV_II_52_0_BIT | DV_II_56_0_BIT);
    mask &= (((w[51] >> 29) ^ (w[52] >> 29)) & 1).wrapping_sub(1)
        | !(DV_I_48_0_BIT | DV_II_47_0_BIT | DV_II_52_0_BIT | DV_II_53_0_BIT);
    mask &= (((w[52] >> 29) ^ (w[53] >> 29)) & 1).wrapping_sub(1)
        | !(DV_I_49_0_BIT | DV_II_45_0_BIT | DV_II_48_0_BIT | DV_II_53_0_BIT | DV_II_54_0_BIT);
    mask &= (((w[53] >> 29) ^ (w[54] >> 29)) & 1).wrapping_sub(1)
        | !(DV_I_50_0_BIT | DV_II_46_0_BIT | DV_II_49_0_BIT | DV_II_54_0_BIT | DV_II_55_0_BIT);
    mask &= (((w[54] >> 29) ^ (w[55] >> 29)) & 1).wrapping_sub(1)
        | !(DV_I_51_0_BIT | DV_II_47_0_BIT | DV_II_50_0_BIT | DV_II_55_0_BIT | DV_II_56_0_BIT);
    mask &= (((w[55] >> 29) ^ (w[56] >> 29)) & 1).wrapping_sub(1)
        | !(DV_I_52_0_BIT | DV_II_48_0_BIT | DV_II_51_0_BIT | DV_II_56_0_BIT);
    mask &=
        (((w[56] >> 29) ^ (w[57] >> 29)) & 1).wrapping_sub(1) | !(DV_II_49_0_BIT | DV_II_52_0_BIT);
    mask &=
        (((w[57] >> 29) ^ (w[58] >> 29)) & 1).wrapping_sub(1) | !(DV_II_50_0_BIT | DV_II_53_0_BIT);

    mask &= (((w[48] >> 4) ^ (w[51] >> 29)) & 1).wrapping_sub(1)
        | !(DV_I_48_0_BIT | DV_I_50_0_BIT | DV_I_52_0_BIT | DV_II_46_0_BIT | DV_II_52_0_BIT);
    mask &= (((w[49] >> 4) ^ (w[52] >> 29)) & 1).wrapping_sub(1)
        | !(DV_I_49_0_BIT | DV_I_51_0_BIT | DV_II_45_0_BIT | DV_II_47_0_BIT | DV_II_53_0_BIT);
    mask &= (((w[50] >> 4) ^ (w[53] >> 29)) & 1).wrapping_sub(1)
        | !(DV_I_50_0_BIT | DV_I_52_0_BIT | DV_II_46_0_BIT | DV_II_48_0_BIT | DV_II_54_0_BIT);
    mask &= (((w[51] >> 4) ^ (w[54] >> 29)) & 1).wrapping_sub(1)
        | !(DV_I_51_0_BIT | DV_II_47_0_BIT | DV_II_49_0_BIT | DV_II_55_0_BIT);
    mask &= (((w[52] >> 4) ^ (w[55] >> 29)) & 1).wrapping_sub(1)
        | !(DV_I_52_0_BIT | DV_II_48_0_BIT | DV_II_50_0_BIT | DV_II_56_0_BIT);
    mask &=
        (((w[53] >> 4) ^ (w[56] >> 29)) & 1).wrapping_sub(1) | !(DV_II_49_0_BIT | DV_II_51_0_BIT);
    mask &=
        (((w[54] >> 4) ^ (w[57] >> 29)) & 1).wrapping_sub(1) | !(DV_II_50_0_BIT | DV_II_52_0_BIT);
    mask &=
        (((w[55] >> 4) ^ (w[58] >> 29)) & 1).wrapping_sub(1) | !(DV_II_51_0_BIT | DV_II_53_0_BIT);

    mask &= (0u32).wrapping_sub(((w[39] >> 4) ^ (w[40] >> 29)) & 1)
        | !(DV_I_43_0_BIT | DV_II_53_0_BIT | DV_II_55_0_BIT);
    mask &= (0u32).wrapping_sub(((w[40] >> 4) ^ (w[41] >> 29)) & 1)
        | !(DV_I_44_0_BIT | DV_II_54_0_BIT | DV_II_56_0_BIT);
    mask &= (0u32).wrapping_sub(((w[41] >> 4) ^ (w[42] >> 29)) & 1)
        | !(DV_I_43_0_BIT | DV_I_45_0_BIT | DV_II_55_0_BIT);
    mask &= (0u32).wrapping_sub(((w[42] >> 4) ^ (w[43] >> 29)) & 1)
        | !(DV_I_44_0_BIT | DV_I_46_0_BIT | DV_II_56_0_BIT);
    mask &= (0u32).wrapping_sub(((w[43] >> 4) ^ (w[44] >> 29)) & 1)
        | !(DV_I_43_0_BIT | DV_I_45_0_BIT | DV_I_47_0_BIT);
    mask &= (0u32).wrapping_sub(((w[44] >> 4) ^ (w[45] >> 29)) & 1)
        | !(DV_I_44_0_BIT | DV_I_46_0_BIT | DV_I_48_0_BIT);
    mask &= (0u32).wrapping_sub(((w[45] >> 4) ^ (w[46] >> 29)) & 1)
        | !(DV_I_45_0_BIT | DV_I_47_0_BIT | DV_I_49_0_BIT);
    mask &= (0u32).wrapping_sub(((w[46] >> 4) ^ (w[47] >> 29)) & 1)
        | !(DV_I_46_0_BIT | DV_I_48_0_BIT | DV_I_50_0_BIT);

    mask &= (((w[35] >> 4) ^ (w[39] >> 29)) & 1).wrapping_sub(1)
        | !(DV_I_45_0_BIT | DV_I_48_0_BIT | DV_II_47_0_BIT);
    mask &= (((w[36] >> 4) ^ (w[40] >> 29)) & 1).wrapping_sub(1)
        | !(DV_I_46_0_BIT | DV_I_49_0_BIT | DV_II_45_0_BIT | DV_II_48_0_BIT);
    mask &= (((w[37] >> 4) ^ (w[41] >> 29)) & 1).wrapping_sub(1)
        | !(DV_I_47_0_BIT | DV_I_50_0_BIT | DV_II_46_0_BIT | DV_II_49_0_BIT);
    mask &= (((w[38] >> 4) ^ (w[42] >> 29)) & 1).wrapping_sub(1)
        | !(DV_I_48_0_BIT | DV_I_51_0_BIT | DV_II_47_0_BIT | DV_II_50_0_BIT);
    mask &= (((w[39] >> 4) ^ (w[43] >> 29)) & 1).wrapping_sub(1)
        | !(DV_I_49_0_BIT | DV_I_52_0_BIT | DV_II_48_0_BIT | DV_II_51_0_BIT);
    mask &= (((w[40] >> 4) ^ (w[44] >> 29)) & 1).wrapping_sub(1)
        | !(DV_I_50_0_BIT | DV_II_49_0_BIT | DV_II_52_0_BIT);
    mask &= (((w[41] >> 4) ^ (w[45] >> 29)) & 1).wrapping_sub(1)
        | !(DV_I_51_0_BIT | DV_II_45_0_BIT | DV_II_50_0_BIT | DV_II_53_0_BIT);
    mask &= (((w[42] >> 4) ^ (w[46] >> 29)) & 1).wrapping_sub(1)
        | !(DV_I_52_0_BIT | DV_II_46_0_BIT | DV_II_51_0_BIT | DV_II_54_0_BIT);

    mask &=
        (0u32).wrapping_sub(((w[35] >> 1) ^ (w[36] >> 6)) & 1) | !(DV_I_46_2_BIT | DV_I_49_2_BIT);
    mask &= (0u32).wrapping_sub(((w[36] >> 1) ^ (w[37] >> 6)) & 1)
        | !(DV_I_47_2_BIT | DV_I_50_2_BIT | DV_II_46_2_BIT);
    mask &=
        (0u32).wrapping_sub(((w[37] >> 1) ^ (w[38] >> 6)) & 1) | !(DV_I_48_2_BIT | DV_I_51_2_BIT);
    mask &= (0u32).wrapping_sub(((w[38] >> 1) ^ (w[39] >> 6)) & 1) | !(DV_I_49_2_BIT);
    mask &= (0u32).wrapping_sub(((w[39] >> 1) ^ (w[40] >> 6)) & 1)
        | !(DV_I_46_2_BIT | DV_I_50_2_BIT | DV_II_49_2_BIT);
    mask &= (0u32).wrapping_sub(((w[40] >> 1) ^ (w[41] >> 6)) & 1)
        | !(DV_I_47_2_BIT | DV_I_51_2_BIT | DV_II_50_2_BIT);
    mask &= (0u32).wrapping_sub(((w[41] >> 1) ^ (w[42] >> 6)) & 1)
        | !(DV_I_48_2_BIT | DV_II_46_2_BIT | DV_II_51_2_BIT);
    mask &= (0u32).wrapping_sub(((w[42] >> 1) ^ (w[43] >> 6)) & 1) | !(DV_I_49_2_BIT);

    mask &= (0u32).wrapping_sub(((w[47] >> 4) ^ (w[48] >> 29)) & 1)
        | !(DV_I_47_0_BIT | DV_I_49_0_BIT | DV_I_51_0_BIT);
    mask &= (0u32).wrapping_sub(((w[48] >> 4) ^ (w[49] >> 29)) & 1)
        | !(DV_I_48_0_BIT | DV_I_50_0_BIT | DV_I_52_0_BIT);
    mask &= (0u32).wrapping_sub(((w[49] >> 4) ^ (w[50] >> 29)) & 1)
        | !(DV_I_49_0_BIT | DV_I_51_0_BIT | DV_II_45_0_BIT);
    mask &= (0u32).wrapping_sub(((w[50] >> 4) ^ (w[51] >> 29)) & 1)
        | !(DV_I_50_0_BIT | DV_I_52_0_BIT | DV_II_46_0_BIT);
    mask &=
        (0u32).wrapping_sub(((w[51] >> 4) ^ (w[52] >> 29)) & 1) | !(DV_I_51_0_BIT | DV_II_47_0_BIT);
    mask &=
        (0u32).wrapping_sub(((w[52] >> 4) ^ (w[53] >> 29)) & 1) | !(DV_I_52_0_BIT | DV_II_48_0_BIT);
    mask &= (0u32).wrapping_sub(((w[53] >> 4) ^ (w[54] >> 29)) & 1) | !(DV_II_49_0_BIT);
    mask &= (0u32).wrapping_sub(((w[54] >> 4) ^ (w[55] >> 29)) & 1) | !(DV_II_50_0_BIT);

    mask &= (((w[41] >> 6) ^ (w[43] >> 6)) & 1).wrapping_sub(1) | !(DV_I_47_2_BIT);
    mask &= (((w[42] >> 6) ^ (w[44] >> 6)) & 1).wrapping_sub(1) | !(DV_I_46_2_BIT | DV_I_48_2_BIT);
    mask &= (((w[43] >> 6) ^ (w[45] >> 6)) & 1).wrapping_sub(1) | !(DV_I_47_2_BIT | DV_I_49_2_BIT);
    mask &= (((w[44] >> 6) ^ (w[46] >> 6)) & 1).wrapping_sub(1)
        | !(DV_I_46_2_BIT | DV_I_48_2_BIT | DV_I_50_2_BIT);
    mask &= (((w[45] >> 6) ^ (w[47] >> 6)) & 1).wrapping_sub(1)
        | !(DV_I_47_2_BIT | DV_I_49_2_BIT | DV_I_51_2_BIT);
    mask &= (((w[46] >> 6) ^ (w[48] >> 6)) & 1).wrapping_sub(1) | !(DV_I_48_2_BIT | DV_I_50_2_BIT);
    mask &= (((w[47] >> 6) ^ (w[49] >> 6)) & 1).wrapping_sub(1) | !(DV_I_49_2_BIT | DV_I_51_2_BIT);
    mask &= (((w[48] >> 6) ^ (w[50] >> 6)) & 1).wrapping_sub(1) | !(DV_I_50_2_BIT | DV_II_46_2_BIT);

    mask &= (((w[37] >> 4) ^ (w[40] >> 29)) & 1).wrapping_sub(1)
        | !(DV_I_43_0_BIT | DV_I_47_0_BIT | DV_II_46_0_BIT | DV_II_53_0_BIT | DV_II_55_0_BIT);
    mask &= (((w[38] >> 4) ^ (w[41] >> 29)) & 1).wrapping_sub(1)
        | !(DV_I_44_0_BIT | DV_I_48_0_BIT | DV_II_47_0_BIT | DV_II_54_0_BIT | DV_II_56_0_BIT);
    mask &= (((w[39] >> 4) ^ (w[42] >> 29)) & 1).wrapping_sub(1)
        | !(DV_I_43_0_BIT | DV_I_45_0_BIT | DV_I_49_0_BIT | DV_II_48_0_BIT | DV_II_55_0_BIT);

    mask
}
